/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as MavenAGI from "../../../../api/index";
import * as core from "../../../../core";
import { ActionParameter } from "./ActionParameter";

export const Action: core.serialization.ObjectSchema<serializers.Action.Raw, MavenAGI.Action> =
    core.serialization.object({
        id: core.serialization.string(),
        actionSetId: core.serialization.string(),
        appId: core.serialization.string(),
        name: core.serialization.string(),
        description: core.serialization.string(),
        userInteractionRequired: core.serialization.boolean(),
        buttonName: core.serialization.string().optional(),
        requiredUserContextFieldNames: core.serialization.set(core.serialization.string()),
        userFormParameters: core.serialization.list(ActionParameter),
    });

export declare namespace Action {
    interface Raw {
        id: string;
        actionSetId: string;
        appId: string;
        name: string;
        description: string;
        userInteractionRequired: boolean;
        buttonName?: string | null;
        requiredUserContextFieldNames: string[];
        userFormParameters: ActionParameter.Raw[];
    }
}
