/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as MavenAGI from "../../../../api/index";
import * as core from "../../../../core";

export const PreconditionGroupOperator: core.serialization.Schema<
    serializers.PreconditionGroupOperator.Raw,
    MavenAGI.PreconditionGroupOperator
> = core.serialization.enum_(["AND", "OR"]);

export declare namespace PreconditionGroupOperator {
    type Raw = "AND" | "OR";
}
