// This file was auto-generated by Fern from our API Definition.

import type * as MavenAGI from "../../../../api/index";
import * as core from "../../../../core";
import type * as serializers from "../../../index";
import { SegmentStatus } from "./SegmentStatus";

export const SegmentFilter: core.serialization.ObjectSchema<serializers.SegmentFilter.Raw, MavenAGI.SegmentFilter> =
    core.serialization.object({
        name: core.serialization.string().optional(),
        description: core.serialization.string().optional(),
        statuses: core.serialization.list(SegmentStatus).optional(),
    });

export declare namespace SegmentFilter {
    export interface Raw {
        name?: string | null;
        description?: string | null;
        statuses?: SegmentStatus.Raw[] | null;
    }
}
