// This file was auto-generated by Fern from our API Definition.

import type * as MavenAGI from "../../../../api/index";
import * as core from "../../../../core";
import type * as serializers from "../../../index";
import { BaseCappedPaginatedRequest } from "../../commons/types/BaseCappedPaginatedRequest";
import { SegmentField } from "./SegmentField";
import { SegmentFilter } from "./SegmentFilter";

export const SegmentsSearchRequest: core.serialization.ObjectSchema<
    serializers.SegmentsSearchRequest.Raw,
    MavenAGI.SegmentsSearchRequest
> = core.serialization
    .object({
        sort: SegmentField.optional(),
        filter: SegmentFilter.optional(),
    })
    .extend(BaseCappedPaginatedRequest);

export declare namespace SegmentsSearchRequest {
    export interface Raw extends BaseCappedPaginatedRequest.Raw {
        sort?: SegmentField.Raw | null;
        filter?: SegmentFilter.Raw | null;
    }
}
