// This file was auto-generated by Fern from our API Definition.

export interface CommitAssetUploadRequest {
    /** MD5 hex digest of the uploaded file. Required for assets attached to knowledge documents. Used to verify blob integrity at ingestion time. */
    checksum?: string;
}
