/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface BaseInboxSearchRequest {
    /** Page number to return, defaults to 0 */
    page?: number;
    /** The size of the page to return, defaults to 20 */
    size?: number;
}
