// This file was auto-generated by Fern from our API Definition.

import * as MavenAGI from "../../../index";

export interface InboxFilter {
    /** List of inbox item statuses to filter by. */
    statuses?: MavenAGI.InboxItemStatus[];
    /** List of inbox item types to filter by. */
    type?: MavenAGI.InboxItemType[];
    /** Filter for items created after this timestamp. */
    createdAfter?: Date;
    /** Filter for items created before this timestamp. */
    createdBefore?: Date;
}
