/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as MavenAGI from "../../../index";

export interface InboxSearchResponse extends MavenAGI.Page {
    /** The list of inbox items returned in the search response. */
    content: MavenAGI.InboxItem[];
}
