// This file was auto-generated by Fern from our API Definition.

import type * as MavenAGI from "../../../../api/index";
import * as core from "../../../../core";
import type * as serializers from "../../../index";

export const SessionTokenRequest: core.serialization.ObjectSchema<
    serializers.SessionTokenRequest.Raw,
    MavenAGI.SessionTokenRequest
> = core.serialization.object({
    ttlSeconds: core.serialization.number(),
});

export declare namespace SessionTokenRequest {
    export interface Raw {
        ttlSeconds: number;
    }
}
