// This file was auto-generated by Fern from our API Definition.

import type * as MavenAGI from "../../../../api/index";
import * as core from "../../../../core";
import type * as serializers from "../../../index";

export const SessionTokenResponse: core.serialization.ObjectSchema<
    serializers.SessionTokenResponse.Raw,
    MavenAGI.SessionTokenResponse
> = core.serialization.object({
    sessionToken: core.serialization.string(),
    expiresAt: core.serialization.date(),
});

export declare namespace SessionTokenResponse {
    export interface Raw {
        sessionToken: string;
        expiresAt: string;
    }
}
