/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type SourceType = "WEB" | "API" | "SYSTEM";
export const SourceType = {
    Web: "WEB",
    Api: "API",
    System: "SYSTEM",
} as const;
