/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as errors from "../../../../errors/index";
import * as MavenAGI from "../../../index";

export class NotFoundError extends errors.MavenAGIError {
    constructor(body: MavenAGI.ErrorMessage) {
        super({
            message: "NotFoundError",
            statusCode: 404,
            body: body,
        });
        Object.setPrototypeOf(this, NotFoundError.prototype);
    }
}
