/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as errors from "../../../../errors/index";
import * as MavenAGI from "../../../index";

export class ServerError extends errors.MavenAGIError {
    constructor(body: MavenAGI.ErrorMessage) {
        super({
            message: "ServerError",
            statusCode: 500,
            body: body,
        });
        Object.setPrototypeOf(this, ServerError.prototype);
    }
}
