/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as MavenAGI from "../../../../api/index";
import * as core from "../../../../core";
import { AgentCapabilityType } from "./AgentCapabilityType";
import { AgentCapabilityField } from "./AgentCapabilityField";
import { BasePaginatedRequest } from "../../commons/types/BasePaginatedRequest";

export const AgentCapabilityListRequest: core.serialization.ObjectSchema<
    serializers.AgentCapabilityListRequest.Raw,
    MavenAGI.AgentCapabilityListRequest
> = core.serialization
    .object({
        capabilityType: AgentCapabilityType.optional(),
        pinned: core.serialization.boolean().optional(),
        enabled: core.serialization.boolean().optional(),
        integrationIds: core.serialization.list(core.serialization.string()).optional(),
        description: core.serialization.string().optionalNullable(),
        userInteractionRequired: core.serialization.boolean().optional(),
        sortId: AgentCapabilityField.optional(),
    })
    .extend(BasePaginatedRequest);

export declare namespace AgentCapabilityListRequest {
    export interface Raw extends BasePaginatedRequest.Raw {
        capabilityType?: AgentCapabilityType.Raw | null;
        pinned?: boolean | null;
        enabled?: boolean | null;
        integrationIds?: string[] | null;
        description?: (string | null) | null;
        userInteractionRequired?: boolean | null;
        sortId?: AgentCapabilityField.Raw | null;
    }
}
