/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as MavenAGI from "../../../../api/index";
import * as core from "../../../../core";
import { TriggerType } from "./TriggerType";
import { AgentCapabilityBase } from "./AgentCapabilityBase";

export const TriggerCapability: core.serialization.ObjectSchema<
    serializers.TriggerCapability.Raw,
    MavenAGI.TriggerCapability
> = core.serialization
    .object({
        triggerType: TriggerType,
    })
    .extend(AgentCapabilityBase);

export declare namespace TriggerCapability {
    export interface Raw extends AgentCapabilityBase.Raw {
        triggerType: TriggerType.Raw;
    }
}
