// This file was auto-generated by Fern from our API Definition.

import * as serializers from "../../../index";
import * as MavenAGI from "../../../../api/index";
import * as core from "../../../../core";

export const BaseOrganization: core.serialization.ObjectSchema<
    serializers.BaseOrganization.Raw,
    MavenAGI.BaseOrganization
> = core.serialization.object({
    name: core.serialization.string(),
    defaultLanguage: core.serialization.string(),
});

export declare namespace BaseOrganization {
    export interface Raw {
        name: string;
        defaultLanguage: string;
    }
}
