// This file was auto-generated by Fern from our API Definition.

import * as serializers from "../../../index";
import * as MavenAGI from "../../../../api/index";
import * as core from "../../../../core";
import { TimeInterval } from "./TimeInterval";
import { AgentUserColumnDefinition } from "./AgentUserColumnDefinition";
import { AgentUserAnalyticsRequest } from "./AgentUserAnalyticsRequest";

export const AgentUserTableRequest: core.serialization.ObjectSchema<
    serializers.AgentUserTableRequest.Raw,
    MavenAGI.AgentUserTableRequest
> = core.serialization
    .object({
        timeGrouping: TimeInterval.optional(),
        columnDefinitions: core.serialization.list(AgentUserColumnDefinition),
    })
    .extend(AgentUserAnalyticsRequest);

export declare namespace AgentUserTableRequest {
    export interface Raw extends AgentUserAnalyticsRequest.Raw {
        timeGrouping?: TimeInterval.Raw | null;
        columnDefinitions: AgentUserColumnDefinition.Raw[];
    }
}
