// This file was auto-generated by Fern from our API Definition.

import type * as MavenAGI from "../../../../api/index";
import * as core from "../../../../core";
import type * as serializers from "../../../index";
import { AgentUserField } from "../../users/types/AgentUserField";
import { RowIdentifierBase } from "./RowIdentifierBase";

export const AgentUserRowIdentifier: core.serialization.ObjectSchema<
    serializers.AgentUserRowIdentifier.Raw,
    MavenAGI.AgentUserRowIdentifier
> = core.serialization
    .object({
        field: AgentUserField,
    })
    .extend(RowIdentifierBase);

export declare namespace AgentUserRowIdentifier {
    export interface Raw extends RowIdentifierBase.Raw {
        field: AgentUserField.Raw;
    }
}
