// This file was auto-generated by Fern from our API Definition.

import type * as MavenAGI from "../../../../api/index";
import * as core from "../../../../core";
import type * as serializers from "../../../index";
import { EntityId } from "../../commons/types/EntityId";
import { ConversationField } from "../../conversation/types/ConversationField";
import { GroupByBase } from "./GroupByBase";
import { Range } from "./Range";

export const ConversationGroupBy: core.serialization.ObjectSchema<
    serializers.ConversationGroupBy.Raw,
    MavenAGI.ConversationGroupBy
> = core.serialization
    .object({
        field: ConversationField,
        intelligentFieldId: EntityId.optional(),
        ranges: core.serialization.list(Range).optional(),
    })
    .extend(GroupByBase);

export declare namespace ConversationGroupBy {
    export interface Raw extends GroupByBase.Raw {
        field: ConversationField.Raw;
        intelligentFieldId?: EntityId.Raw | null;
        ranges?: Range.Raw[] | null;
    }
}
