/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as MavenAGI from "../../../../api/index";
import * as core from "../../../../core";
import { ConversationGroupBy } from "./ConversationGroupBy";
import { ConversationMetric } from "./ConversationMetric";
import { ConversationAnalyticsRequest } from "./ConversationAnalyticsRequest";

export const ConversationPieChartRequest: core.serialization.ObjectSchema<
    serializers.ConversationPieChartRequest.Raw,
    MavenAGI.ConversationPieChartRequest
> = core.serialization
    .object({
        groupBy: ConversationGroupBy,
        metric: ConversationMetric,
    })
    .extend(ConversationAnalyticsRequest);

export declare namespace ConversationPieChartRequest {
    export interface Raw extends ConversationAnalyticsRequest.Raw {
        groupBy: ConversationGroupBy.Raw;
        metric: ConversationMetric.Raw;
    }
}
