/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as MavenAGI from "../../../../api/index";
import * as core from "../../../../core";
import { TimeInterval } from "./TimeInterval";
import { ConversationGroupBy } from "./ConversationGroupBy";
import { ConversationMetric } from "./ConversationMetric";
import { ConversationAnalyticsRequest } from "./ConversationAnalyticsRequest";

export const DateHistogramRequest: core.serialization.ObjectSchema<
    serializers.DateHistogramRequest.Raw,
    MavenAGI.DateHistogramRequest
> = core.serialization
    .object({
        timeInterval: TimeInterval,
        groupBy: ConversationGroupBy.optional(),
        metric: ConversationMetric,
    })
    .extend(ConversationAnalyticsRequest);

export declare namespace DateHistogramRequest {
    interface Raw extends ConversationAnalyticsRequest.Raw {
        timeInterval: TimeInterval.Raw;
        groupBy?: ConversationGroupBy.Raw | null;
        metric: ConversationMetric.Raw;
    }
}
