// This file was auto-generated by Fern from our API Definition.

import type * as MavenAGI from "../../../../api/index";
import * as core from "../../../../core";
import type * as serializers from "../../../index";
import { ColumnDefinitionBase } from "./ColumnDefinitionBase";
import { EventMetric } from "./EventMetric";

export const EventColumnDefinition: core.serialization.ObjectSchema<
    serializers.EventColumnDefinition.Raw,
    MavenAGI.EventColumnDefinition
> = core.serialization
    .object({
        metric: EventMetric,
    })
    .extend(ColumnDefinitionBase);

export declare namespace EventColumnDefinition {
    export interface Raw extends ColumnDefinitionBase.Raw {
        metric: EventMetric.Raw;
    }
}
