// This file was auto-generated by Fern from our API Definition.

import type * as MavenAGI from "../../../../api/index";
import * as core from "../../../../core";
import type * as serializers from "../../../index";
import { EventBarChartRequest } from "./EventBarChartRequest";
import { EventDateHistogramRequest } from "./EventDateHistogramRequest";
import { EventPieChartRequest } from "./EventPieChartRequest";

export const EventChartRequest: core.serialization.Schema<
    serializers.EventChartRequest.Raw,
    MavenAGI.EventChartRequest
> = core.serialization
    .union("type", {
        pieChart: EventPieChartRequest,
        dateHistogram: EventDateHistogramRequest,
        barChart: EventBarChartRequest,
    })
    .transform<MavenAGI.EventChartRequest>({
        transform: (value) => value,
        untransform: (value) => value,
    });

export declare namespace EventChartRequest {
    export type Raw = EventChartRequest.PieChart | EventChartRequest.DateHistogram | EventChartRequest.BarChart;

    export interface PieChart extends EventPieChartRequest.Raw {
        type: "pieChart";
    }

    export interface DateHistogram extends EventDateHistogramRequest.Raw {
        type: "dateHistogram";
    }

    export interface BarChart extends EventBarChartRequest.Raw {
        type: "barChart";
    }
}
