// This file was auto-generated by Fern from our API Definition.

import type * as MavenAGI from "../../../../api/index";
import * as core from "../../../../core";
import type * as serializers from "../../../index";

export const FeedbackCount: core.serialization.ObjectSchema<serializers.FeedbackCount.Raw, MavenAGI.FeedbackCount> =
    core.serialization.object({});

export declare namespace FeedbackCount {
    export type Raw = {};
}
