// This file was auto-generated by Fern from our API Definition.

import type * as MavenAGI from "../../../../api/index";
import * as core from "../../../../core";
import type * as serializers from "../../../index";
import { FeedbackCount } from "./FeedbackCount";
import { FeedbackDistinctCount } from "./FeedbackDistinctCount";

export const FeedbackMetric: core.serialization.Schema<serializers.FeedbackMetric.Raw, MavenAGI.FeedbackMetric> =
    core.serialization
        .union("type", {
            count: FeedbackCount,
            distinctCount: FeedbackDistinctCount,
        })
        .transform<MavenAGI.FeedbackMetric>({
            transform: (value) => value,
            untransform: (value) => value,
        });

export declare namespace FeedbackMetric {
    export type Raw = FeedbackMetric.Count | FeedbackMetric.DistinctCount;

    export interface Count extends FeedbackCount.Raw {
        type: "count";
    }

    export interface DistinctCount extends FeedbackDistinctCount.Raw {
        type: "distinctCount";
    }
}
