/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as MavenAGI from "../../../../api/index";
import * as core from "../../../../core";

export const FeedbackCount: core.serialization.ObjectSchema<serializers.FeedbackCount.Raw, MavenAGI.FeedbackCount> =
    core.serialization.object({});

export declare namespace FeedbackCount {
    export interface Raw {}
}
