/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as MavenAGI from "../../../../api/index";
import * as core from "../../../../core";
import { BasicMetric } from "./BasicMetric";

export const Median: core.serialization.ObjectSchema<serializers.Median.Raw, MavenAGI.Median> = core.serialization
    .object({})
    .extend(BasicMetric);

export declare namespace Median {
    interface Raw extends BasicMetric.Raw {}
}
