// This file was auto-generated by Fern from our API Definition.

import type * as MavenAGI from "../../../../api/index";
import * as core from "../../../../core";
import type * as serializers from "../../../index";

export const TableResponseBase: core.serialization.ObjectSchema<
    serializers.TableResponseBase.Raw,
    MavenAGI.TableResponseBase
> = core.serialization.object({
    headers: core.serialization.list(core.serialization.string()),
});

export declare namespace TableResponseBase {
    export interface Raw {
        headers: string[];
    }
}
