// This file was auto-generated by Fern from our API Definition.

/**
 * Audio chunk to send into the conversation.
 */
export interface UserAudioChunk {
    type: "user_audio_chunk";
    /** Base64-encoded audio data */
    data: string;
}
