/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as MavenAGI from "../../../../api/index";
import * as core from "../../../../core";

export const BrowserType: core.serialization.Schema<serializers.BrowserType.Raw, MavenAGI.BrowserType> =
    core.serialization.enum_(["CHROME", "FIREFOX", "SAFARI", "OPERA", "EDGE", "OTHER"]);

export declare namespace BrowserType {
    export type Raw = "CHROME" | "FIREFOX" | "SAFARI" | "OPERA" | "EDGE" | "OTHER";
}
