/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as MavenAGI from "../../../../api/index";
import * as core from "../../../../core";
import { EntityIdBase } from "../../commons/types/EntityIdBase";
import { UserEventName } from "./UserEventName";
import { UserInfoBase } from "./UserInfoBase";
import { FeedbackInfo } from "./FeedbackInfo";
import { PageInfo } from "./PageInfo";
import { EventBaseNoId } from "./EventBaseNoId";

export const NovelUserEvent: core.serialization.ObjectSchema<serializers.NovelUserEvent.Raw, MavenAGI.NovelUserEvent> =
    core.serialization
        .object({
            id: EntityIdBase,
            eventName: UserEventName,
            userInfo: UserInfoBase,
            feedbackInfo: core.serialization.list(FeedbackInfo).optional(),
            pageInfo: PageInfo.optional(),
        })
        .extend(EventBaseNoId);

export declare namespace NovelUserEvent {
    export interface Raw extends EventBaseNoId.Raw {
        id: EntityIdBase.Raw;
        eventName: UserEventName.Raw;
        userInfo: UserInfoBase.Raw;
        feedbackInfo?: FeedbackInfo.Raw[] | null;
        pageInfo?: PageInfo.Raw | null;
    }
}
