/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as MavenAGI from "../../../../api/index";
import * as core from "../../../../core";
import { EntityId } from "../../commons/types/EntityId";

export const UserInfo: core.serialization.ObjectSchema<serializers.UserInfo.Raw, MavenAGI.UserInfo> =
    core.serialization.object({
        id: EntityId.optional(),
    });

export declare namespace UserInfo {
    export interface Raw {
        id?: EntityId.Raw | null;
    }
}
