/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as MavenAGI from "../../../../api/index";
import * as core from "../../../../core";
import { EntityIdBase } from "../../commons/types/EntityIdBase";

export const UserInfoBase: core.serialization.ObjectSchema<serializers.UserInfoBase.Raw, MavenAGI.UserInfoBase> =
    core.serialization.object({
        id: EntityIdBase,
    });

export declare namespace UserInfoBase {
    export interface Raw {
        id: EntityIdBase.Raw;
    }
}
