// This file was auto-generated by Fern from our API Definition.

import type * as MavenAGI from "../../../../../api/index";
import * as core from "../../../../../core";
import type * as serializers from "../../../../index";
import { CapabilityStatus } from "../../../commons/types/CapabilityStatus";
import { EntityIdBase } from "../../../commons/types/EntityIdBase";
import { EnumOption } from "../../types/EnumOption";

export const IntelligentFieldPatchRequest: core.serialization.Schema<
    serializers.IntelligentFieldPatchRequest.Raw,
    MavenAGI.IntelligentFieldPatchRequest
> = core.serialization.object({
    appId: core.serialization.string().optional(),
    definition: core.serialization.string().optional(),
    status: CapabilityStatus.optional(),
    description: core.serialization.string().optional(),
    enumOptions: core.serialization.list(EnumOption).optional(),
    variantId: EntityIdBase.optional(),
    variantAppId: core.serialization.string().optional(),
});

export declare namespace IntelligentFieldPatchRequest {
    export interface Raw {
        appId?: string | null;
        definition?: string | null;
        status?: CapabilityStatus.Raw | null;
        description?: string | null;
        enumOptions?: EnumOption.Raw[] | null;
        variantId?: EntityIdBase.Raw | null;
        variantAppId?: string | null;
    }
}
