// This file was auto-generated by Fern from our API Definition.

import type * as MavenAGI from "../../../../api/index";
import * as core from "../../../../core";
import type * as serializers from "../../../index";

export const EnumOption: core.serialization.ObjectSchema<serializers.EnumOption.Raw, MavenAGI.EnumOption> =
    core.serialization.object({
        value: core.serialization.string(),
        label: core.serialization.string().optional(),
        description: core.serialization.string().optional(),
    });

export declare namespace EnumOption {
    export interface Raw {
        value: string;
        label?: string | null;
        description?: string | null;
    }
}
