// This file was auto-generated by Fern from our API Definition.

import type * as MavenAGI from "../../../../api/index";
import * as core from "../../../../core";
import type * as serializers from "../../../index";
import { EntityIdWithoutAgent } from "../../commons/types/EntityIdWithoutAgent";
import { EntityType } from "../../commons/types/EntityType";
import { IntelligentFieldCore } from "./IntelligentFieldCore";

export const IntelligentFieldBase: core.serialization.ObjectSchema<
    serializers.IntelligentFieldBase.Raw,
    MavenAGI.IntelligentFieldBase
> = core.serialization
    .object({
        entityType: EntityType,
        variantId: EntityIdWithoutAgent.optional(),
    })
    .extend(IntelligentFieldCore);

export declare namespace IntelligentFieldBase {
    export interface Raw extends IntelligentFieldCore.Raw {
        entityType: EntityType.Raw;
        variantId?: EntityIdWithoutAgent.Raw | null;
    }
}
