// This file was auto-generated by Fern from our API Definition.

import type * as MavenAGI from "../../../../api/index";
import * as core from "../../../../core";
import type * as serializers from "../../../index";
import { CharterSummary } from "../../charters/types/CharterSummary";
import { IntelligentFieldResponse } from "./IntelligentFieldResponse";

export const IntelligentFieldDetailResponse: core.serialization.ObjectSchema<
    serializers.IntelligentFieldDetailResponse.Raw,
    MavenAGI.IntelligentFieldDetailResponse
> = core.serialization
    .object({
        referencingCharters: core.serialization.list(CharterSummary).optional(),
    })
    .extend(IntelligentFieldResponse);

export declare namespace IntelligentFieldDetailResponse {
    export interface Raw extends IntelligentFieldResponse.Raw {
        referencingCharters?: CharterSummary.Raw[] | null;
    }
}
