// This file was auto-generated by Fern from our API Definition.

import type * as MavenAGI from "../../../../api/index";
import * as core from "../../../../core";
import type * as serializers from "../../../index";
import { IntelligentFieldValueResponse } from "../../commons/types/IntelligentFieldValueResponse";
import { Page } from "../../commons/types/Page";

export const IntelligentFieldValueSearchResponse: core.serialization.ObjectSchema<
    serializers.IntelligentFieldValueSearchResponse.Raw,
    MavenAGI.IntelligentFieldValueSearchResponse
> = core.serialization
    .object({
        values: core.serialization.list(IntelligentFieldValueResponse),
    })
    .extend(Page);

export declare namespace IntelligentFieldValueSearchResponse {
    export interface Raw extends Page.Raw {
        values: IntelligentFieldValueResponse.Raw[];
    }
}
