// This file was auto-generated by Fern from our API Definition.

import type * as MavenAGI from "../../../../../api/index";
import * as core from "../../../../../core";
import type * as serializers from "../../../../index";

export const InboxItemApplyTagsRequest: core.serialization.Schema<
    serializers.InboxItemApplyTagsRequest.Raw,
    MavenAGI.InboxItemApplyTagsRequest
> = core.serialization.object({
    appId: core.serialization.string().optional(),
    tags: core.serialization.set(core.serialization.string()),
});

export declare namespace InboxItemApplyTagsRequest {
    export interface Raw {
        appId?: string | null;
        tags: string[];
    }
}
