// This file was auto-generated by Fern from our API Definition.

import type * as MavenAGI from "../../../../api/index";
import * as core from "../../../../core";
import type * as serializers from "../../../index";
import { CustomerStatus } from "./CustomerStatus";

export const CustomerFilter: core.serialization.ObjectSchema<serializers.CustomerFilter.Raw, MavenAGI.CustomerFilter> =
    core.serialization.object({
        search: core.serialization.string().optional(),
        statuses: core.serialization.list(CustomerStatus).optional(),
        assignees: core.serialization.list(core.serialization.string()).optional(),
        members: core.serialization.list(core.serialization.string()).optional(),
    });

export declare namespace CustomerFilter {
    export interface Raw {
        search?: string | null;
        statuses?: CustomerStatus.Raw[] | null;
        assignees?: string[] | null;
        members?: string[] | null;
    }
}
