// This file was auto-generated by Fern from our API Definition.

import type * as MavenAGI from "../../../../api/index";
import * as core from "../../../../core";
import type * as serializers from "../../../index";
import { CustomerStatus } from "./CustomerStatus";

export const CustomerPatchRequest: core.serialization.ObjectSchema<
    serializers.CustomerPatchRequest.Raw,
    MavenAGI.CustomerPatchRequest
> = core.serialization.object({
    appId: core.serialization.string().optional(),
    name: core.serialization.string().optional(),
    description: core.serialization.string().optional(),
    status: CustomerStatus.optional(),
    metadata: core.serialization.record(core.serialization.string(), core.serialization.string()).optional(),
    assignees: core.serialization.set(core.serialization.string()).optional(),
    members: core.serialization.set(core.serialization.string()).optional(),
});

export declare namespace CustomerPatchRequest {
    export interface Raw {
        appId?: string | null;
        name?: string | null;
        description?: string | null;
        status?: CustomerStatus.Raw | null;
        metadata?: Record<string, string> | null;
        assignees?: string[] | null;
        members?: string[] | null;
    }
}
