// This file was auto-generated by Fern from our API Definition.

import type * as MavenAGI from "../../../index";

/**
 * @example
 *     {
 *         number: 0,
 *         size: 2,
 *         totalElements: 2,
 *         totalPages: 1,
 *         capabilities: [{
 *                 capabilityId: {
 *                     referenceId: "ticket-priority",
 *                     appId: "my-billing-system",
 *                     organizationId: "acme",
 *                     agentId: "support",
 *                     type: MavenAGI.EntityType.IntelligentField
 *                 },
 *                 capabilityType: MavenAGI.CapabilityType.IntelligentField,
 *                 name: "Ticket priority",
 *                 description: "How urgent the conversation is",
 *                 status: MavenAGI.CapabilityStatus.Inactive,
 *                 createdAt: new Date("2026-01-16T08:00:00.000Z"),
 *                 updatedAt: new Date("2026-01-16T08:00:00.000Z")
 *             }, {
 *                 capabilityId: {
 *                     referenceId: "get-balance",
 *                     appId: "my-billing-system",
 *                     organizationId: "acme",
 *                     agentId: "support",
 *                     type: MavenAGI.EntityType.Action
 *                 },
 *                 capabilityType: MavenAGI.CapabilityType.Action,
 *                 name: "Check balance",
 *                 description: "Looks up the customer's current account balance",
 *                 status: MavenAGI.CapabilityStatus.Active,
 *                 createdAt: new Date("2026-01-15T10:30:00.000Z"),
 *                 updatedAt: new Date("2026-01-15T10:30:00.000Z")
 *             }]
 *     }
 */
export interface CapabilitiesSearchResponse extends MavenAGI.Page {
    /** The capabilities on this page, in the order the request asked for. */
    capabilities: MavenAGI.CapabilitySummary[];
}
