/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as MavenAGI from "../../../../api/index";
import * as core from "../../../../core";

export const AgentField: core.serialization.Schema<serializers.AgentField.Raw, MavenAGI.AgentField> =
    core.serialization.enum_(["CREATED_AT", "ENVIRONMENT"]);

export declare namespace AgentField {
    export type Raw = "CREATED_AT" | "ENVIRONMENT";
}
