// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {}
 */
export interface ActionGetRequest {
    /** The App ID of the action to get. If not provided the ID of the calling app will be used. */
    appId?: string;
}
