// This file was auto-generated by Fern from our API Definition.

import type * as MavenAGI from "../../../index";

/**
 * Context items (knowledge bases and actions) a charter makes available.
 */
export interface CharterReferences {
    /**
     * The knowledge bases this charter makes available, each optionally narrowed to a
     * subset of that knowledge base's documents.
     *
     * At most one entry per knowledge base. Maximum 50 knowledge bases per charter.
     *
     * On a write, supplying this replaces the charter's whole knowledge base set. A response
     * always populates it.
     */
    knowledgeBases?: MavenAGI.CharterKnowledgeBaseReference[];
    /**
     * The IDs of actions this charter makes available.
     * Maximum 50 actions per charter.
     */
    actionIds: MavenAGI.EntityId[];
}
