// This file was auto-generated by Fern from our API Definition.

import type * as MavenAGI from "../../../index";

export interface CharterBase {
    /** Display name for this charter or group. */
    name: string;
    /**
     * ID of the agent variant this charter belongs to, if applicable.
     *
     * On a write this is validated -- an unknown variant is rejected, as is any
     * variant while variant scoping is off for charters -- but not yet applied: the
     * write reaches the agent's live configuration either way.
     */
    variantId?: MavenAGI.EntityIdWithoutAgent;
    /** A plain text description of this charter. If not set, existing description is preserved if present. */
    description?: string;
    /**
     * Optional additional natural language instruction text when this
     * charter matches. Manuals concatenate with ancestor charter manuals
     * before delivery.
     *
     * If not set, existing manual is preserved if present.
     */
    manual?: string;
}
