// This file was auto-generated by Fern from our API Definition.

import type * as MavenAGI from "../../../index";

/**
 * Filters combine with AND: a charter must match every filter given. Within one filter, a
 * charter matches if it references any of the listed IDs. An empty list is the same as
 * omitting the filter.
 */
export interface CharterSearchFilter {
    /** Only return charters referencing these actions. At most 50. */
    actionIds?: MavenAGI.EntityId[];
    /** Only return charters referencing these knowledge bases. At most 50. */
    knowledgeBaseIds?: MavenAGI.EntityId[];
    /**
     * Only return charters whose precondition references these intelligent fields. At most 50.
     * A charter reaches an intelligent field through its precondition, not by referencing it
     * directly the way it does an action or a knowledge base.
     */
    intelligentFieldIds?: MavenAGI.EntityId[];
}
