// This file was auto-generated by Fern from our API Definition.

import type * as MavenAGI from "../../../index";

/**
 * @example
 *     {
 *         segmentId: {
 *             referenceId: "admin-users"
 *         },
 *         name: "Admin users",
 *         precondition: {
 *             preconditionType: "group",
 *             operator: MavenAGI.PreconditionGroupOperator.And,
 *             preconditions: [{
 *                     "preconditionType": "user",
 *                     "key": "userKey"
 *                 }, {
 *                     "preconditionType": "user",
 *                     "key": "userKey2"
 *                 }]
 *         }
 *     }
 */
export interface SegmentRequest extends MavenAGI.SegmentBase {
    /** ID that uniquely identifies this segment */
    segmentId: MavenAGI.EntityIdBase;
    /** Desired status for the segment. If omitted, defaults to ACTIVE. In the future this will become required, so specify ACTIVE or INACTIVE if possible. */
    status?: MavenAGI.SegmentStatus;
}
