// This file was auto-generated by Fern from our API Definition.

export interface SegmentBase {
    /** The name of the segment. */
    name: string;
    /** A plain text description of the segment. */
    description?: string;
}
