// This file was auto-generated by Fern from our API Definition.

import * as MavenAGI from "../../../index";

export interface SegmentPatchRequest {
    /** The App ID of the segment to update. If not provided, the ID of the calling app will be used. */
    appId?: string;
    /** The name of the segment. */
    name?: string;
    /** The precondition that must be met for a conversation message to be included in the segment. */
    precondition?: MavenAGI.Precondition;
    /** The status of the segment. Segments can only be deactivated if they are not set on any actions or active knowledge bases. */
    status?: MavenAGI.SegmentStatus;
}
