// This file was auto-generated by Fern from our API Definition.

import type * as MavenAGI from "../../../index";

/**
 * @example
 *     {
 *         segmentId: {
 *             referenceId: "admin-users",
 *             appId: "auth-app",
 *             organizationId: "acme",
 *             agentId: "support",
 *             type: MavenAGI.EntityType.Segment
 *         },
 *         name: "Admin users",
 *         createdAt: new Date("2025-01-01T00:00:00.000Z"),
 *         updatedAt: new Date("2025-01-15T12:30:00.000Z"),
 *         status: MavenAGI.SegmentStatus.Active,
 *         precondition: {
 *             preconditionType: "group",
 *             operator: MavenAGI.PreconditionGroupOperator.And,
 *             preconditions: [{
 *                     "preconditionType": "user",
 *                     "key": "userKey"
 *                 }, {
 *                     "preconditionType": "user",
 *                     "key": "userKey2"
 *                 }]
 *         }
 *     }
 */
export interface SegmentResponse extends MavenAGI.SegmentBase {
    /** ID that uniquely identifies this segment */
    segmentId: MavenAGI.EntityId;
    /** The date and time when the segment was created. */
    createdAt: Date;
    /** The date and time when the segment was last updated. */
    updatedAt: Date;
    /**
     * The status of the segment.
     *
     * - ACTIVE: Segment is in use and will be evaluated for matching user questions.
     * - INACTIVE: Segment is not in use but can be reactivated.
     * - DELETED: Segment has been soft deleted. Excluded from searches and cannot be modified.
     */
    status: MavenAGI.SegmentStatus;
}
