// This file was auto-generated by Fern from our API Definition.

import type * as MavenAGI from "../../../index";

/**
 * Filter criteria for searching segments.
 */
export interface SegmentFilter {
    /**
     * Filter segments by name. Case-insensitive substring match.
     * Empty string returns all results.
     */
    name?: string;
    /**
     * Filter segments by description. Case-insensitive substring match.
     * Empty string returns all results.
     */
    description?: string;
    /**
     * Filter segments by status. Returns segments matching any of the provided statuses.
     * Empty list returns all non-deleted results.
     */
    statuses?: MavenAGI.SegmentStatus[];
}
