/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as MavenAGI from "../../../index";

export interface ConversationGroupBy extends MavenAGI.GroupByBase {
    /** Field used for data grouping. */
    field: MavenAGI.ConversationField;
    /** Numeric ranges for grouping data into predefined buckets. Applies only to numeric fields. */
    ranges?: MavenAGI.Range[];
}
