// This file was auto-generated by Fern from our API Definition.

import type * as MavenAGI from "../../../index";

export interface EventBarChartRequest extends MavenAGI.EventAnalyticsRequest {
    /** Determines how data is grouped along the x-axis. Each unique value forms a separate bar. */
    barDefinition: MavenAGI.EventGroupBy;
    /** Metric defining the y-axis values for the bar chart. */
    metric: MavenAGI.EventMetric;
    /**
     * Optionally defines vertical grouping within each bar, producing multiple series.
     * If omitted, a single series is generated.
     */
    verticalGrouping?: MavenAGI.EventGroupBy;
}
