// This file was auto-generated by Fern from our API Definition.

import type * as MavenAGI from "../../../index";

export interface EventDateHistogramRequest extends MavenAGI.EventAnalyticsRequest {
    /** Time-based grouping interval (e.g., HOUR, DAY, WEEK) for the date histogram. */
    timeInterval: MavenAGI.TimeInterval;
    /** Groups data before applying calculations, forming a separate time series for each group. */
    groupBy?: MavenAGI.EventGroupBy;
    /** Defines the y-axis values for the date histogram. */
    metric: MavenAGI.EventMetric;
}
