// This file was auto-generated by Fern from our API Definition.

import type * as MavenAGI from "../../../index";

export interface EventRowIdentifier extends MavenAGI.RowIdentifierBase {
    /** Field this grouping was on. */
    field: MavenAGI.EventField;
}
