// This file was auto-generated by Fern from our API Definition.

import type * as MavenAGI from "../../../index";

export interface EventGroupBy extends MavenAGI.GroupByBase {
    /** Field used for data grouping. */
    field: MavenAGI.EventField;
}
