/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as MavenAGI from "../../../index";

export type FieldValue =
    | MavenAGI.FieldValue.DateTime
    | MavenAGI.FieldValue.String
    | MavenAGI.FieldValue.Double
    | MavenAGI.FieldValue.Long
    | MavenAGI.FieldValue.Range
    | MavenAGI.FieldValue.Boolean
    | MavenAGI.FieldValue.EntityId;

export namespace FieldValue {
    export interface DateTime {
        type: "dateTime";
        value: Date;
    }

    export interface String {
        type: "string";
        value: string;
    }

    export interface Double {
        type: "double";
        value: number;
    }

    export interface Long {
        type: "long";
        value: number;
    }

    export interface Range extends MavenAGI.Range {
        type: "range";
    }

    export interface Boolean {
        type: "boolean";
        value: boolean;
    }

    export interface EntityId extends MavenAGI.EntityIdFilter {
        type: "entityId";
    }
}
