// This file was auto-generated by Fern from our API Definition.

import type * as MavenAGI from "../../../index";

export interface Organization extends MavenAGI.BaseOrganization {
    /** ID that uniquely identifies this organization */
    organizationId: MavenAGI.EntityIdBase;
}
