// This file was auto-generated by Fern from our API Definition.

import type * as MavenAGI from "../../../index";

export interface EventTriggerBase {
    /** The description of what the event trigger does, shown in the Maven Dashboard */
    description: string;
    /**
     * The type of event trigger this app wishes to handle.
     *
     * Conversation triggers fire when a conversation is created, after each additional message, and upon deletion events.
     * There is a small delay before trigger execution to allow time for conversation analysis to complete.
     *
     * Feedback can not be modified, so the feedback trigger fires immediately after feedback is created.
     */
    type: MavenAGI.EventTriggerType;
}
