// This file was auto-generated by Fern from our API Definition.

import type * as MavenAGI from "../../../index";

/**
 * @example
 *     {
 *         triggerId: {
 *             referenceId: "store-in-snowflake"
 *         },
 *         description: "Stores conversation data in Snowflake",
 *         type: MavenAGI.EventTriggerType.ConversationCreated
 *     }
 */
export interface EventTriggerRequest extends MavenAGI.EventTriggerBase {
    /** ID that uniquely identifies this event trigger */
    triggerId: MavenAGI.EntityIdBase;
}
