// This file was auto-generated by Fern from our API Definition.

import type * as MavenAGI from "../../../index";

/**
 * @example
 *     {
 *         triggerId: {
 *             referenceId: "store-in-snowflake",
 *             appId: "snowflake",
 *             organizationId: "acme",
 *             agentId: "support",
 *             type: MavenAGI.EntityType.EventTrigger
 *         },
 *         name: "Store in Snowflake",
 *         description: "Stores conversation data in Snowflake",
 *         type: MavenAGI.EventTriggerType.ConversationCreated,
 *         enabled: true,
 *         createdAt: new Date("2026-01-15T10:30:00.000Z"),
 *         updatedAt: new Date("2026-01-15T10:30:00.000Z"),
 *         status: MavenAGI.CapabilityStatus.Active
 *     }
 */
export interface EventTriggerResponse extends MavenAGI.EventTriggerBase, MavenAGI.CapabilityBase {
    /** ID that uniquely identifies this event trigger */
    triggerId: MavenAGI.EntityId;
    /**
     * Deprecated. Superseded by `status`, which says the same thing for every capability type.
     *
     * Whether this trigger will be called by Maven.
     */
    enabled: boolean;
}
