// This file was auto-generated by Fern from our API Definition.

import * as MavenAGI from "../../../index";

export interface EventTriggersSearchResponse extends MavenAGI.Page {
    triggers: MavenAGI.EventTriggerResponse[];
}
