/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type TriggerField = "CreatedAt" | "Enabled";
export const TriggerField = {
    CreatedAt: "CreatedAt",
    Enabled: "Enabled",
} as const;
