/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as MavenAGI from "../../../../index";

/**
 * @example
 *     {
 *         appId: "appId",
 *         itemType: "DUPLICATE_DOCUMENT"
 *     }
 */
export interface InboxItemIgnoreRequest {
    /**
     * The App ID of the inbox item fix to ignore
     */
    appId: string;
    /**
     * The type of the inbox item to retrieve
     */
    itemType: MavenAGI.InboxItemType;
}
