// This file was auto-generated by Fern from our API Definition.

import type * as MavenAGI from "../../../../api/index";
import * as core from "../../../../core";
import type * as serializers from "../../../index";
import { EntityIdWithoutAgent } from "../../commons/types/EntityIdWithoutAgent";
import { LlmInclusionStatus } from "../../commons/types/LlmInclusionStatus";

export const KnowledgeDocumentFilter: core.serialization.ObjectSchema<
    serializers.KnowledgeDocumentFilter.Raw,
    MavenAGI.KnowledgeDocumentFilter
> = core.serialization.object({
    search: core.serialization.string().optional(),
    title: core.serialization.string().optional(),
    url: core.serialization.string().optional(),
    createdAfter: core.serialization.date().optional(),
    createdBefore: core.serialization.date().optional(),
    appIds: core.serialization.list(core.serialization.string()).optional(),
    knowledgeBaseVersionId: EntityIdWithoutAgent.optional(),
    llmInclusionStatus: core.serialization.list(LlmInclusionStatus).optional(),
});

export declare namespace KnowledgeDocumentFilter {
    export interface Raw {
        search?: string | null;
        title?: string | null;
        url?: string | null;
        createdAfter?: string | null;
        createdBefore?: string | null;
        appIds?: string[] | null;
        knowledgeBaseVersionId?: EntityIdWithoutAgent.Raw | null;
        llmInclusionStatus?: LlmInclusionStatus.Raw[] | null;
    }
}
