// This file was auto-generated by Fern from our API Definition.

import type * as MavenAGI from "../../../../api/index";
import * as core from "../../../../core";
import type * as serializers from "../../../index";

export const KnowledgeBaseVersionFinalizeStatus: core.serialization.Schema<
    serializers.KnowledgeBaseVersionFinalizeStatus.Raw,
    MavenAGI.KnowledgeBaseVersionFinalizeStatus
> = core.serialization.enum_(["SUCCEEDED", "FAILED"]);

export declare namespace KnowledgeBaseVersionFinalizeStatus {
    export type Raw = "SUCCEEDED" | "FAILED";
}
