// This file was auto-generated by Fern from our API Definition.

import * as serializers from "../../../index";
import * as MavenAGI from "../../../../api/index";
import * as core from "../../../../core";
import { EntityIdBase } from "../../commons/types/EntityIdBase";
import { EntityIdWithoutAgent } from "../../commons/types/EntityIdWithoutAgent";
import { KnowledgeDocumentContentType } from "./KnowledgeDocumentContentType";
import { BaseKnowledgeDocument } from "./BaseKnowledgeDocument";

export const KnowledgeDocumentRequest: core.serialization.ObjectSchema<
    serializers.KnowledgeDocumentRequest.Raw,
    MavenAGI.KnowledgeDocumentRequest
> = core.serialization
    .object({
        knowledgeDocumentId: EntityIdBase,
        versionId: EntityIdWithoutAgent.optional(),
        contentType: KnowledgeDocumentContentType,
        title: core.serialization.string(),
        content: core.serialization.string(),
        metadata: core.serialization.record(core.serialization.string(), core.serialization.string()).optional(),
        createdAt: core.serialization.date().optional(),
        updatedAt: core.serialization.date().optional(),
    })
    .extend(BaseKnowledgeDocument);

export declare namespace KnowledgeDocumentRequest {
    export interface Raw extends BaseKnowledgeDocument.Raw {
        knowledgeDocumentId: EntityIdBase.Raw;
        versionId?: EntityIdWithoutAgent.Raw | null;
        contentType: KnowledgeDocumentContentType.Raw;
        title: string;
        content: string;
        metadata?: Record<string, string> | null;
        createdAt?: string | null;
        updatedAt?: string | null;
    }
}
