// This file was auto-generated by Fern from our API Definition.

import type * as MavenAGI from "../../../../api/index";
import * as core from "../../../../core";
import type * as serializers from "../../../index";
import { EntityId } from "../../commons/types/EntityId";
import { KnowledgeBaseVersionRequest } from "./KnowledgeBaseVersionRequest";
import { KnowledgeBaseVersionStatus } from "./KnowledgeBaseVersionStatus";

export const KnowledgeBaseVersion: core.serialization.ObjectSchema<
    serializers.KnowledgeBaseVersion.Raw,
    MavenAGI.KnowledgeBaseVersion
> = core.serialization
    .object({
        versionId: EntityId,
        status: KnowledgeBaseVersionStatus,
        errorMessage: core.serialization.string().optional(),
        createdAt: core.serialization.date(),
        updatedAt: core.serialization.date(),
    })
    .extend(KnowledgeBaseVersionRequest);

export declare namespace KnowledgeBaseVersion {
    export interface Raw extends KnowledgeBaseVersionRequest.Raw {
        versionId: EntityId.Raw;
        status: KnowledgeBaseVersionStatus.Raw;
        errorMessage?: string | null;
        createdAt: string;
        updatedAt: string;
    }
}
