/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as MavenAGI from "../../../../api/index";
import * as core from "../../../../core";
import { KnowledgeBaseVersionType } from "./KnowledgeBaseVersionType";

export const KnowledgeBaseVersion: core.serialization.ObjectSchema<
    serializers.KnowledgeBaseVersion.Raw,
    MavenAGI.KnowledgeBaseVersion
> = core.serialization.object({
    type: KnowledgeBaseVersionType,
});

export declare namespace KnowledgeBaseVersion {
    interface Raw {
        type: KnowledgeBaseVersionType.Raw;
    }
}
