/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as MavenAGI from "../../../../api/index";
import * as core from "../../../../core";
import { EntityId } from "../../commons/types/EntityId";
import { BaseKnowledgeDocument } from "./BaseKnowledgeDocument";

export const KnowledgeDocumentSearchResponse: core.serialization.ObjectSchema<
    serializers.KnowledgeDocumentSearchResponse.Raw,
    MavenAGI.KnowledgeDocumentSearchResponse
> = core.serialization
    .object({
        knowledgeDocumentId: EntityId,
        metadata: core.serialization.record(core.serialization.string(), core.serialization.string()),
    })
    .extend(BaseKnowledgeDocument);

export declare namespace KnowledgeDocumentSearchResponse {
    export interface Raw extends BaseKnowledgeDocument.Raw {
        knowledgeDocumentId: EntityId.Raw;
        metadata: Record<string, string>;
    }
}
