/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as MavenAGI from "../../../../api/index";
import * as core from "../../../../core";
import { KnowledgeBaseType } from "./KnowledgeBaseType";
import { KnowledgeBaseId } from "./KnowledgeBaseId";

export const KnowledgeBase: core.serialization.ObjectSchema<serializers.KnowledgeBase.Raw, MavenAGI.KnowledgeBase> =
    core.serialization
        .object({
            displayName: core.serialization.property("display_name", core.serialization.string()),
            type: KnowledgeBaseType,
            url: core.serialization.string().optional(),
        })
        .extend(KnowledgeBaseId);

export declare namespace KnowledgeBase {
    interface Raw extends KnowledgeBaseId.Raw {
        display_name: string;
        type: KnowledgeBaseType.Raw;
        url?: string | null;
    }
}
