// This file was auto-generated by Fern from our API Definition.

import type * as MavenAGI from "../../../../api/index";
import * as core from "../../../../core";
import type * as serializers from "../../../index";
import { Page } from "../../commons/types/Page";
import { KnowledgeDocumentSearchResponse } from "./KnowledgeDocumentSearchResponse";

export const KnowledgeDocumentsResponse: core.serialization.ObjectSchema<
    serializers.KnowledgeDocumentsResponse.Raw,
    MavenAGI.KnowledgeDocumentsResponse
> = core.serialization
    .object({
        knowledgeDocuments: core.serialization.list(KnowledgeDocumentSearchResponse),
    })
    .extend(Page);

export declare namespace KnowledgeDocumentsResponse {
    export interface Raw extends Page.Raw {
        knowledgeDocuments: KnowledgeDocumentSearchResponse.Raw[];
    }
}
