/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as MavenAGI from "../../../../api/index";
import * as core from "../../../../core";

export const KnowledgeBaseField: core.serialization.Schema<
    serializers.KnowledgeBaseField.Raw,
    MavenAGI.KnowledgeBaseField
> = core.serialization.enum_(["Title", "UpdatedAt"]);

export declare namespace KnowledgeBaseField {
    export type Raw = "Title" | "UpdatedAt";
}
