// This file was auto-generated by Fern from our API Definition.

import type * as MavenAGI from "../../../../api/index";
import * as core from "../../../../core";
import type * as serializers from "../../../index";

export const KnowledgeBaseField: core.serialization.Schema<
    serializers.KnowledgeBaseField.Raw,
    MavenAGI.KnowledgeBaseField
> = core.serialization.enum_(["Title", "CreatedAt", "UpdatedAt"]);

export declare namespace KnowledgeBaseField {
    export type Raw = "Title" | "CreatedAt" | "UpdatedAt";
}
