/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type AgentUserField = "CreatedAt" | "UpdatedAt";
export const AgentUserField = {
    CreatedAt: "CreatedAt",
    UpdatedAt: "UpdatedAt",
} as const;
