// This file was auto-generated by Fern from our API Definition.

import type * as MavenAGI from "../../../../api/index";
import * as core from "../../../../core";
import type * as serializers from "../../../index";

export const AppCategory: core.serialization.Schema<serializers.AppCategory.Raw, MavenAGI.AppCategory> =
    core.serialization.enum_([
        "COMMUNICATION",
        "CUSTOMER_SUPPORT",
        "DATA_STORAGE",
        "INTERNAL_TOOLS",
        "KNOWLEDGE",
        "PROJECT_MANAGEMENT",
        "VOICE",
    ]);

export declare namespace AppCategory {
    export type Raw =
        | "COMMUNICATION"
        | "CUSTOMER_SUPPORT"
        | "DATA_STORAGE"
        | "INTERNAL_TOOLS"
        | "KNOWLEDGE"
        | "PROJECT_MANAGEMENT"
        | "VOICE";
}
