/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as MavenAGI from "../../../../api/index";
import * as core from "../../../../core";

export const AudioSubscribeEvent: core.serialization.ObjectSchema<
    serializers.AudioSubscribeEvent.Raw,
    MavenAGI.AudioSubscribeEvent
> = core.serialization.object({
    audioContent: core.serialization.string(),
});

export declare namespace AudioSubscribeEvent {
    export interface Raw {
        audioContent: string;
    }
}
