// This file was auto-generated by Fern from our API Definition.

import type * as MavenAGI from "../../../index";

/**
 * @example
 *     {
 *         conversationMessageId: {
 *             referenceId: "message-0"
 *         },
 *         userId: {
 *             referenceId: "user-0"
 *         },
 *         text: "How do I reset my password?",
 *         attachments: [{
 *                 type: "image/png",
 *                 content: "iVBORw0KGgo..."
 *             }],
 *         transientData: {
 *             "userToken": "abcdef123",
 *             "queryApiKey": "foobar456"
 *         },
 *         timezone: "America/New_York"
 *     }
 */
export interface AskRequest {
    /** Externally supplied ID to uniquely identify this message within the conversation. If a message with this ID already exists it will be reused and will not be updated. */
    conversationMessageId: MavenAGI.EntityIdBase;
    /** Externally supplied ID to uniquely identify the user that created this message */
    userId: MavenAGI.EntityIdBase;
    /** The text of the message */
    text: string;
    /**
     * The attachments to the message. Image attachments will be sent to the LLM as additional data.
     * Non-image attachments can be stored and downloaded from the API but will not be sent to the LLM.
     */
    attachments?: MavenAGI.AttachmentRequest[];
    /** Transient data which the Maven platform will not persist. This data will only be forwarded to actions taken by this ask request. For example, one may put in user tokens as transient data. */
    transientData?: Record<string, string>;
    /** IANA timezone identifier (e.g. "America/New_York", "Europe/London") to be used for time-based operations in the conversation. */
    timezone?: string;
    /**
     * Key-value metadata to persist on the user message created by this request. Unlike
     * `transientData` (which is never persisted) this is stored and returned when the message
     * is read back via the API or dashboard, and unlike user data it is not sent to the LLM.
     * Applied only when the message is first created — if `conversationMessageId` already
     * exists the message is reused and its metadata is not updated. Keys and values are strings
     * with a maximum length of 500 characters each.
     */
    appMetadata?: Record<string, string>;
}
