/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as MavenAGI from "../../../index";

export interface BotActionFormResponse {
    id: string;
    formLabel: string;
    fields: MavenAGI.ActionFormField[];
    submitLabel: string;
}
