/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as MavenAGI from "../../../index";

export type BotResponse = MavenAGI.BotResponse.Text | MavenAGI.BotResponse.ActionLink;

export declare namespace BotResponse {
    interface Text extends MavenAGI.TextBotResponse {
        type: "text";
    }

    interface ActionLink extends MavenAGI.ActionLinkBotResponse {
        type: "actionLink";
    }
}
