/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type Capability = "MARKDOWN" | "FORMS";

export const Capability = {
    Markdown: "MARKDOWN",
    Forms: "FORMS",
} as const;
