// This file was auto-generated by Fern from our API Definition.

export const ConversationField = {
    Category: "Category",
    FirstResponseTime: "FirstResponseTime",
    HandleTime: "HandleTime",
    HumanAgents: "HumanAgents",
    HumanAgentsWithInserts: "HumanAgentsWithInserts",
    App: "App",
    Sentiment: "Sentiment",
    QualityReason: "QualityReason",
    ResolutionStatus: "ResolutionStatus",
    ResolvedByMaven: "ResolvedByMaven",
    Quality: "Quality",
    Users: "Users",
    ResponseLength: "ResponseLength",
    ThumbsUpCount: "ThumbsUpCount",
    ThumbsDownCount: "ThumbsDownCount",
    InsertCount: "InsertCount",
    Tags: "Tags",
    UserMessageCount: "UserMessageCount",
    BotMessageCount: "BotMessageCount",
    Languages: "Languages",
    Actions: "Actions",
    IncompleteActions: "IncompleteActions",
    ErroredActions: "ErroredActions",
    ActionExecutionCount: "ActionExecutionCount",
    ActionErrorCount: "ActionErrorCount",
    Charters: "Charters",
    Sources: "Sources",
    CreatedAt: "CreatedAt",
    PredictedNps: "PredictedNPS",
    Csat: "Csat",
    OrganizationId: "OrganizationId",
    AgentId: "AgentId",
    /**
     * The environment configured on the agent: DEMO, STAGING, or PRODUCTION. Constant within a
     * single agent, so it only separates conversations on a cross-agent request. */
    AgentEnvironment: "AgentEnvironment",
    InboxItems: "InboxItems",
    InvolvedApps: "InvolvedApps",
    /**
     * In development, part of agent versioning. The agent variant the conversation is pinned
     * to (its `variantId`). A conversation from before the agent's conversations were pinned
     * has none; grouping puts those under `BEFORE_VERSIONING`. In a table row a variant is an
     * `entityId` value and `BEFORE_VERSIONING` a `string` value. */
    Variant: "Variant",
    /**
     * Selects an intelligent field rather than a built-in conversation field.
     * When used, `intelligentFieldId` must also be set to identify which field.
     * Grouping by it splits that one field's conversations by value; to split conversations by
     * which fields they have, use `IntelligentFields`. */
    IntelligentField: "IntelligentField",
    /**
     * Groups conversations by each intelligent field that has a value on them: one bucket per
     * field, keyed by the field as an `entityId` value. A conversation with three fields counts
     * once under each, as with `Actions`. A field counts when the conversation has a value for
     * it, an undetermined one included: the same conversations an `intelligentFields`
     * `EXISTS` condition matches. Only conversation-level fields are on a conversation.
     *
     * Unlike `IntelligentField`, it takes no `intelligentFieldId` and doesn't look at values.
     * Combine it with `Variant` to see which fields each variant's conversations have.
     *
     * It only works as a grouping: a metric targeting it, such as a `distinctCount`, is
     * rejected with a 400. */
    IntelligentFields: "IntelligentFields",
} as const;
export type ConversationField = (typeof ConversationField)[keyof typeof ConversationField] | string;
