/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as MavenAGI from "../../../index.js";

export interface ConversationsSearchRequest extends MavenAGI.BasePaginatedRequest {
    sort?: MavenAGI.ConversationField;
    filter?: MavenAGI.ConversationFilter;
}
