// This file was auto-generated by Fern from our API Definition.

import * as MavenAGI from "../../../index";

export interface DeliverConversationMessageRequest {
    /** The ID of the conversation to deliver the message to. Message delivery will fail if the conversation does not have the `ASYNC` capability or if it is not `open`. */
    conversationId: MavenAGI.EntityIdWithoutAgent;
    /** The message to deliver. */
    message: MavenAGI.ConversationMessageRequest;
}
