// This file was auto-generated by Fern from our API Definition.

export const FeedbackField = {
    Type: "Type",
    CreatedBy: "CreatedBy",
    CreatedAt: "CreatedAt",
    App: "App",
} as const;
export type FeedbackField = (typeof FeedbackField)[keyof typeof FeedbackField];
