// This file was auto-generated by Fern from our API Definition.

import * as MavenAGI from "../../../index";

export interface FeedbackFilter {
    search?: string;
    createdAfter?: Date;
    createdBefore?: Date;
    users?: string[];
    apps?: string[];
    types?: MavenAGI.FeedbackType[];
}
