/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as MavenAGI from "../../../index.js";

export interface FeedbackFilter {
    search?: string;
    createdAfter?: string;
    createdBefore?: string;
    users?: string[];
    apps?: string[];
    types?: MavenAGI.FeedbackType[];
}
