// This file was auto-generated by Fern from our API Definition.

import type * as MavenAGI from "../../../index";

/**
 * Filter conversations by intelligent field values. All conditions are ANDed.
 */
export interface IntelligentFieldFilter {
    /** List of conditions to filter by. All conditions must match (AND logic). */
    conditions: MavenAGI.IntelligentFieldSearchCondition[];
}
