// This file was auto-generated by Fern from our API Definition.

export const NumericConversationField = {
    ThumbsUpCount: "ThumbsUpCount",
    ThumbsDownCount: "ThumbsDownCount",
    InsertCount: "InsertCount",
    UserMessageCount: "UserMessageCount",
    BotMessageCount: "BotMessageCount",
    HandleTime: "HandleTime",
    FirstResponseTime: "FirstResponseTime",
    PredictedNps: "PredictedNPS",
    Csat: "Csat",
    ActionExecutionCount: "ActionExecutionCount",
    ActionErrorCount: "ActionErrorCount",
    /**
     * Selects a NUMBER-validated intelligent field rather than a built-in numeric field.
     * When used, `intelligentFieldId` must also be set to identify which field. */
    IntelligentField: "IntelligentField",
} as const;
export type NumericConversationField =
    | (typeof NumericConversationField)[keyof typeof NumericConversationField]
    | string;
