/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type QualityReason =
    | "MISSING_KNOWLEDGE"
    | "MISSING_USER_INFORMATION"
    | "MISSING_ACTION"
    | "NEEDS_USER_CLARIFICATION"
    | "UNSUPPORTED_FORMAT"
    | "GREAT_ANSWER"
    | "INTERRUPTED"
    | "UNSUPPORTED_USER_BEHAVIOR"
    | "UNKNOWN";
export const QualityReason = {
    MissingKnowledge: "MISSING_KNOWLEDGE",
    MissingUserInformation: "MISSING_USER_INFORMATION",
    MissingAction: "MISSING_ACTION",
    NeedsUserClarification: "NEEDS_USER_CLARIFICATION",
    UnsupportedFormat: "UNSUPPORTED_FORMAT",
    GreatAnswer: "GREAT_ANSWER",
    Interrupted: "INTERRUPTED",
    UnsupportedUserBehavior: "UNSUPPORTED_USER_BEHAVIOR",
    Unknown: "UNKNOWN",
} as const;
