/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as MavenAGI from "../../../index.js";

export type StreamResponse =
    | MavenAGI.StreamResponse.Text
    | MavenAGI.StreamResponse.Action
    | MavenAGI.StreamResponse.Chart
    | MavenAGI.StreamResponse.Metadata
    | MavenAGI.StreamResponse.Start
    | MavenAGI.StreamResponse.End;

export namespace StreamResponse {
    export interface Text extends MavenAGI.AskStreamTextEvent {
        eventType: "text";
    }

    export interface Action extends MavenAGI.AskStreamActionEvent {
        eventType: "action";
    }

    export interface Chart extends MavenAGI.AskStreamChartEvent {
        eventType: "chart";
    }

    export interface Metadata extends MavenAGI.AskStreamMetadataEvent {
        eventType: "metadata";
    }

    export interface Start extends MavenAGI.AskStreamStartEvent {
        eventType: "start";
    }

    export interface End extends MavenAGI.AskStreamEndEvent {
        eventType: "end";
    }
}
