// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         appId: "conversation-owning-app",
 *         values: {
 *             "key": "newValue"
 *         }
 *     }
 */
export interface UpdateMetadataRequest {
    /** The App ID of the conversation to modify metadata for. If not provided the ID of the calling app will be used. */
    appId?: string;
    /**
     * Set of 16 key-value pairs that can be attached to an object. This can be useful for storing
     * additional information about the object in a structured format, and querying for objects
     * via API or the dashboard.
     *
     * Keys and values are strings with a maximum length of 500 characters.
     */
    values: Record<string, string>;
}
