/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {
 *         appId: "conversation-owning-app",
 *         values: {
 *             "key": "newValue"
 *         }
 *     }
 */
export interface UpdateMetadataRequest {
    /** The App ID of the conversation to modify metadata for. If not provided the ID of the calling app will be used. */
    appId?: string;
    /** The metadata values to add to the conversation. */
    values: Record<string, string>;
}
