/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as MavenAGI from "../../../index";

export interface UserMessageBase extends MavenAGI.ConversationMessageBase {
    /** The text of the message. Cannot be empty */
    text: string;
    userMessageType: MavenAGI.UserConversationMessageType;
}
