// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         translatedText: "Hola mundo"
 *     }
 */
export interface TranslationResponse {
    /** The translated text */
    translatedText: string;
}
