// This file was auto-generated by Fern from our API Definition.

export const CustomerStatus = {
    Active: "ACTIVE",
    Inactive: "INACTIVE",
} as const;
export type CustomerStatus = (typeof CustomerStatus)[keyof typeof CustomerStatus];
