// This file was auto-generated by Fern from our API Definition.

import type * as MavenAGI from "../../../index";

export interface CustomerPatchRequest {
    /** The App ID of the customer to update. If not provided, the ID of the calling app will be used. */
    appId?: string;
    /** The name of the customer. */
    name?: string;
    /** The description of the customer. */
    description?: string;
    /**
     * Whether or not the customer is in active use.
     *
     * Only active customers will be available for agent interactions.
     */
    status?: MavenAGI.CustomerStatus;
    /** Metadata associated with the customer. If not provided, the existing metadata will be preserved. */
    metadata?: Record<string, string>;
    /** Set of agent user IDs to assign to this customer. If provided, replaces all existing assignees. */
    assignees?: Set<string>;
    /** Set of agent user IDs who are members of this customer. If provided, replaces all existing members. */
    members?: Set<string>;
}
