// This file was auto-generated by Fern from our API Definition.

import type * as MavenAGI from "../../../../index";

/**
 * @example
 *     {}
 */
export interface PatchCapabilityByTypeRequest {
    /** The app that owns the capability. Defaults to the calling app. */
    appId?: string;
    /**
     * The agent variant to stage an intelligent field's status change in, by reference ID.
     * Required for an intelligent field on an agent with versioned intelligent fields; a
     * request that omits it there is rejected with reason `VARIANT_REQUIRED`.
     * The other capability types aren't versioned and are the same in every variant,
     * though a named variant must still exist.
     */
    variantReferenceId?: string;
    /** The app that owns the agent variant. Defaults to the calling app. */
    variantAppId?: string;
    /**
     * Whether the agent uses this capability. Use ACTIVE to start and INACTIVE to stop;
     * deleting is done through the delete endpoint, so DELETED is rejected here.
     */
    status?: MavenAGI.CapabilityStatus;
}
