/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as MavenAGI from "../../../../api/index";
import * as core from "../../../../core";

export const TriggerPartialUpdate: core.serialization.ObjectSchema<
    serializers.TriggerPartialUpdate.Raw,
    MavenAGI.TriggerPartialUpdate
> = core.serialization.object({
    enabled: core.serialization.boolean().optional(),
});

export declare namespace TriggerPartialUpdate {
    export interface Raw {
        enabled?: boolean | null;
    }
}
