/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as MavenAGI from "../../../../api/index";
import * as core from "../../../../core";
import { ActionFormAttachment } from "./ActionFormAttachment";

export const ActionFormRequestParamValue: core.serialization.Schema<
    serializers.ActionFormRequestParamValue.Raw,
    MavenAGI.ActionFormRequestParamValue
> = core.serialization.undiscriminatedUnion([core.serialization.unknown(), ActionFormAttachment]);

export declare namespace ActionFormRequestParamValue {
    export type Raw = unknown | ActionFormAttachment.Raw;
}
