// This file was auto-generated by Fern from our API Definition.

import type * as MavenAGI from "../../../../api/index";
import * as core from "../../../../core";
import type * as serializers from "../../../index";
import { BotObjectResponse } from "../../commons/types/BotObjectResponse";

export const AskStreamObjectEvent: core.serialization.ObjectSchema<
    serializers.AskStreamObjectEvent.Raw,
    MavenAGI.AskStreamObjectEvent
> = core.serialization.object({}).extend(BotObjectResponse);

export declare namespace AskStreamObjectEvent {
    export interface Raw extends BotObjectResponse.Raw {}
}
