/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as MavenAGI from "../../../../api/index";
import * as core from "../../../../core";

export const Attachment: core.serialization.ObjectSchema<serializers.Attachment.Raw, MavenAGI.Attachment> =
    core.serialization.object({
        type: core.serialization.string(),
        content: core.serialization.string(),
    });

export declare namespace Attachment {
    export interface Raw {
        type: string;
        content: string;
    }
}
