/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as MavenAGI from "../../../../api/index";
import * as core from "../../../../core";
import { BotConversationMessageType } from "./BotConversationMessageType";
import { BotResponse } from "./BotResponse";
import { ConversationMessageBase } from "./ConversationMessageBase";

export const BotMessage: core.serialization.ObjectSchema<serializers.BotMessage.Raw, MavenAGI.BotMessage> =
    core.serialization
        .object({
            botMessageType: BotConversationMessageType,
            responses: core.serialization.list(BotResponse),
        })
        .extend(ConversationMessageBase);

export declare namespace BotMessage {
    interface Raw extends ConversationMessageBase.Raw {
        botMessageType: BotConversationMessageType.Raw;
        responses: BotResponse.Raw[];
    }
}
