// This file was auto-generated by Fern from our API Definition.

import type * as MavenAGI from "../../../../api/index";
import * as core from "../../../../core";
import type * as serializers from "../../../index";
import { AttachmentRequest } from "../../commons/types/AttachmentRequest";
import { EntityIdBase } from "../../commons/types/EntityIdBase";
import { UserMessageBase } from "../../commons/types/UserMessageBase";

export const ConversationMessageRequest: core.serialization.ObjectSchema<
    serializers.ConversationMessageRequest.Raw,
    MavenAGI.ConversationMessageRequest
> = core.serialization
    .object({
        conversationMessageId: EntityIdBase,
        attachments: core.serialization.list(AttachmentRequest).optional(),
    })
    .extend(UserMessageBase);

export declare namespace ConversationMessageRequest {
    export interface Raw extends UserMessageBase.Raw {
        conversationMessageId: EntityIdBase.Raw;
        attachments?: AttachmentRequest.Raw[] | null;
    }
}
