// This file was auto-generated by Fern from our API Definition.

import type * as MavenAGI from "../../../../api/index";
import * as core from "../../../../core";
import type * as serializers from "../../../index";
import { AttachmentRequest } from "../../commons/types/AttachmentRequest";

export const ConversationPatchRequest: core.serialization.ObjectSchema<
    serializers.ConversationPatchRequest.Raw,
    MavenAGI.ConversationPatchRequest
> = core.serialization.object({
    appId: core.serialization.string().optional(),
    open: core.serialization.boolean().optional(),
    llmEnabled: core.serialization.boolean().optional(),
    attachments: core.serialization.list(AttachmentRequest).optional(),
});

export declare namespace ConversationPatchRequest {
    export interface Raw {
        appId?: string | null;
        open?: boolean | null;
        llmEnabled?: boolean | null;
        attachments?: AttachmentRequest.Raw[] | null;
    }
}
