/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as MavenAGI from "../../../../api/index";
import * as core from "../../../../core";

export const DeliveryStatus: core.serialization.Schema<serializers.DeliveryStatus.Raw, MavenAGI.DeliveryStatus> =
    core.serialization.enum_(["DELIVERED", "FAILED", "QUEUED"]);

export declare namespace DeliveryStatus {
    export type Raw = "DELIVERED" | "FAILED" | "QUEUED";
}
