// This file was auto-generated by Fern from our API Definition.

import * as serializers from "../../../index";
import * as MavenAGI from "../../../../api/index";
import * as core from "../../../../core";
import { DeliveryStatus } from "./DeliveryStatus";

export const DeliverMessageResponse: core.serialization.ObjectSchema<
    serializers.DeliverMessageResponse.Raw,
    MavenAGI.DeliverMessageResponse
> = core.serialization.object({
    status: DeliveryStatus,
});

export declare namespace DeliverMessageResponse {
    export interface Raw {
        status: DeliveryStatus.Raw;
    }
}
