// This file was auto-generated by Fern from our API Definition.

import * as serializers from "../../../index";
import * as MavenAGI from "../../../../api/index";
import * as core from "../../../../core";
import { EntityIdWithoutAgent } from "../../commons/types/EntityIdWithoutAgent";
import { ConversationMessageRequest } from "./ConversationMessageRequest";

export const DeliverUserMessageRequest: core.serialization.ObjectSchema<
    serializers.DeliverUserMessageRequest.Raw,
    MavenAGI.DeliverUserMessageRequest
> = core.serialization.object({
    userId: EntityIdWithoutAgent,
    message: ConversationMessageRequest,
});

export declare namespace DeliverUserMessageRequest {
    export interface Raw {
        userId: EntityIdWithoutAgent.Raw;
        message: ConversationMessageRequest.Raw;
    }
}
