/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as MavenAGI from "../../../../api/index";
import * as core from "../../../../core";

export const NumericConversationField: core.serialization.Schema<
    serializers.NumericConversationField.Raw,
    MavenAGI.NumericConversationField
> = core.serialization.enum_([
    "ThumbsUpCount",
    "ThumbsDownCount",
    "InsertCount",
    "UserMessageCount",
    "HandleTime",
    "FirstResponseTime",
]);

export declare namespace NumericConversationField {
    export type Raw =
        | "ThumbsUpCount"
        | "ThumbsDownCount"
        | "InsertCount"
        | "UserMessageCount"
        | "HandleTime"
        | "FirstResponseTime";
}
