/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as MavenAGI from "../../../../api/index";
import * as core from "../../../../core";

export const QualityReason: core.serialization.Schema<serializers.QualityReason.Raw, MavenAGI.QualityReason> =
    core.serialization.enum_([
        "MISSING_KNOWLEDGE",
        "MISSING_USER_INFORMATION",
        "MISSING_ACTION",
        "NEEDS_USER_CLARIFICATION",
        "UNSUPPORTED_FORMAT",
        "GREAT_ANSWER",
        "INTERRUPTED",
        "UNSUPPORTED_USER_BEHAVIOR",
        "UNKNOWN",
    ]);

export declare namespace QualityReason {
    type Raw =
        | "MISSING_KNOWLEDGE"
        | "MISSING_USER_INFORMATION"
        | "MISSING_ACTION"
        | "NEEDS_USER_CLARIFICATION"
        | "UNSUPPORTED_FORMAT"
        | "GREAT_ANSWER"
        | "INTERRUPTED"
        | "UNSUPPORTED_USER_BEHAVIOR"
        | "UNKNOWN";
}
