// This file was auto-generated by Fern from our API Definition.

import type * as MavenAGI from "../../../../api/index";
import * as core from "../../../../core";
import type * as serializers from "../../../index";
import { EntityIdBase } from "../../commons/types/EntityIdBase";

export const InitiateAssetUploadResponse: core.serialization.ObjectSchema<
    serializers.InitiateAssetUploadResponse.Raw,
    MavenAGI.InitiateAssetUploadResponse
> = core.serialization.object({
    assetId: EntityIdBase,
    uploadUrl: core.serialization.string(),
    expiresAt: core.serialization.date(),
});

export declare namespace InitiateAssetUploadResponse {
    export interface Raw {
        assetId: EntityIdBase.Raw;
        uploadUrl: string;
        expiresAt: string;
    }
}
