// This file was auto-generated by Fern from our API Definition.

import type * as MavenAGI from "../../../index";

export interface IntelligentFieldBase extends MavenAGI.IntelligentFieldCore {
    /** Target entity type for evaluation. CONVERSATION is supported, and AGENT_USER is supported for agents with user-level intelligent fields enabled. The backend will return an error for other types. */
    entityType: MavenAGI.EntityType;
    /** On a request, the agent variant to stage the write in. On a response, the variant the request named, if any; absent when it named none. */
    variantId?: MavenAGI.EntityIdWithoutAgent;
}
