// This file was auto-generated by Fern from our API Definition.

export const AppCapability = {
    Actions: "ACTIONS",
    Bailout: "BAILOUT",
    KnowledgeBases: "KNOWLEDGE_BASES",
    Personalization: "PERSONALIZATION",
    Triggers: "TRIGGERS",
} as const;
export type AppCapability = (typeof AppCapability)[keyof typeof AppCapability];
