// This file was auto-generated by Fern from our API Definition.

import type * as MavenAGI from "../../../index";

export interface AppsResponse extends MavenAGI.Page {
    /** The page of apps matching the filter. */
    apps: MavenAGI.MarketplaceApp[];
    /**
     * How many apps fall into each visibility and category, across everything visible to the
     * agent rather than just this page. Present only when `filterCountEnabled` was set.
     */
    allAppsCountByFilter?: MavenAGI.CountByFilterResult;
    /**
     * The same breakdown restricted to apps installed on this agent. Present only when
     * `filterCountEnabled` was set.
     */
    installedAppsCountByFilter?: MavenAGI.CountByFilterResult;
}
