// This file was auto-generated by Fern from our API Definition.

import type * as MavenAGI from "../../../index";

/**
 * Narrows the apps returned by a directory search. Every field is optional; omitting all of them
 * returns every app visible to the agent. Fields combine with AND, and list fields match any of
 * their values.
 */
export interface AppsFilter {
    /** Case-insensitive substring match against an app's id, name, or description. */
    search?: string;
    /** Only return apps with one of these visibilities. */
    visibility?: MavenAGI.AppVisibility[];
    /**
     * Only return apps that are installed on this agent, or only those that are not. Omit to
     * return both.
     */
    installed?: MavenAGI.AppInstalled;
    /** Only return apps tagged with one of these categories. */
    category?: MavenAGI.AppCategory[];
    /** Only return apps offering one of these capabilities. */
    capability?: MavenAGI.AppCapability[];
    /**
     * Also compute `allAppsCountByFilter` and `installedAppsCountByFilter` on the response.
     * These are the counts a filter sidebar needs, and computing them costs extra queries, so
     * they are off by default.
     */
    filterCountEnabled?: boolean;
}
