// This file was auto-generated by Fern from our API Definition.

import type * as MavenAGI from "../../../index";

/**
 * The fields every app exposes, whatever the surface it is returned from.
 */
export interface BaseApp {
    /** Unique, immutable identifier for the app, used as `appId` everywhere in the API. */
    id: string;
    /** Display name shown in the app directory. */
    name: string;
    /** Id of the organization that authored the app, which is not the organization it is installed in. */
    developerOrganizationId: string;
    /** Public profile of the authoring organization, for attribution in the directory. */
    creator?: MavenAGI.DeveloperOrganization;
    /**
     * Who can discover the app. PUBLIC is listed for every organization; PRIVATE is limited to the
     * authoring organization and any organization it has been shared with; IN_DEVELOPMENT is not
     * yet listed.
     */
    visibility: MavenAGI.AppVisibility;
    /** Full description shown on the app's detail page. */
    description?: string;
    /** One-line summary shown on the app's card in the directory listing. */
    shortDescription?: string;
    /** URL of the app's logo. Presigned and short-lived when the logo is stored by Maven. */
    logoUrl?: string;
    /** Categories the app is filed under in the directory. */
    categories: MavenAGI.AppCategory[];
    /** The kinds of functionality the app provides, such as actions, triggers, or knowledge bases. */
    capabilities: MavenAGI.AppCapability[];
    /** Whether this app is an auto-provisioned agent app created for a specific agent. */
    isAgentApp?: boolean;
}
