/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as MavenAGI from "../../../index";

/**
 * The response from the server sent through the WebSocket.
 */
export type SubscribeEvent =
    | MavenAGI.SubscribeEvent.Audio
    | MavenAGI.SubscribeEvent.ControlSessionStart
    | MavenAGI.SubscribeEvent.ControlSessionStop
    | MavenAGI.SubscribeEvent.ControlAudioDone;

export namespace SubscribeEvent {
    export interface Audio extends MavenAGI.AudioSubscribeEvent {
        messageType: "audio";
    }

    export interface ControlSessionStart extends MavenAGI.ControlEvent {
        messageType: "controlSessionStart";
    }

    export interface ControlSessionStop extends MavenAGI.ControlEvent {
        messageType: "controlSessionStop";
    }

    export interface ControlAudioDone extends MavenAGI.ControlEvent {
        messageType: "controlAudioDone";
    }
}
