/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as MavenAGI from "../../../index";

/**
 * @example
 *     {
 *         actionId: {
 *             referenceId: "get-balance",
 *             appId: "my-billing-system",
 *             organizationId: "acme",
 *             agentId: "support",
 *             type: MavenAGI.EntityType.Action
 *         },
 *         name: "Get the user's balance",
 *         description: "This action calls an API to get the user's current balance.",
 *         userInteractionRequired: false,
 *         preconditions: {
 *             requiredUserContextFieldNames: new Set(["my-billing-system.userId"])
 *         },
 *         userFormParameters: []
 *     }
 */
export interface ActionResponse extends MavenAGI.ActionBase {
    /** ID that uniquely identifies this action */
    actionId: MavenAGI.EntityId;
}
