// This file was auto-generated by Fern from our API Definition.

export const AgentEnvironment = {
    Demo: "DEMO",
    Staging: "STAGING",
    Production: "PRODUCTION",
} as const;
export type AgentEnvironment = (typeof AgentEnvironment)[keyof typeof AgentEnvironment];
