// This file was auto-generated by Fern from our API Definition.

export const VoiceTokenType = {
    Webrtc: "webrtc",
    Websocket: "websocket",
} as const;
export type VoiceTokenType = (typeof VoiceTokenType)[keyof typeof VoiceTokenType];
