// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {}
 */
export interface CustomerGetRequest {
    /** The App ID of the customer to get. If not provided, the ID of the calling app will be used. */
    appId?: string;
}
