// This file was auto-generated by Fern from our API Definition.

import type * as MavenAGI from "../../../../api/index";
import * as core from "../../../../core";
import type * as serializers from "../../../index";
import { ServerEventBase } from "./ServerEventBase";

export const Error_: core.serialization.ObjectSchema<serializers.Error_.Raw, MavenAGI.Error_> = core.serialization
    .object({
        type: core.serialization.stringLiteral("error"),
        message: core.serialization.string(),
        code: core.serialization.string(),
    })
    .extend(ServerEventBase);

export declare namespace Error_ {
    export interface Raw extends ServerEventBase.Raw {
        type: "error";
        message: string;
        code: string;
    }
}
