// This file was auto-generated by Fern from our API Definition.

import type * as MavenAGI from "../../../../api/index";
import * as core from "../../../../core";
import type * as serializers from "../../../index";

export const ServerEventBase: core.serialization.ObjectSchema<
    serializers.ServerEventBase.Raw,
    MavenAGI.ServerEventBase
> = core.serialization.object({
    eventId: core.serialization.string(),
});

export declare namespace ServerEventBase {
    export interface Raw {
        eventId: string;
    }
}
