// This file was auto-generated by Fern from our API Definition.

import type * as MavenAGI from "../../../../api/index";
import * as core from "../../../../core";
import type * as serializers from "../../../index";

export const AgentUserField: core.serialization.Schema<serializers.AgentUserField.Raw, MavenAGI.AgentUserField> =
    core.serialization.enum_(["CreatedAt", "UpdatedAt"]);

export declare namespace AgentUserField {
    export type Raw = "CreatedAt" | "UpdatedAt";
}
