// This file was auto-generated by Fern from our API Definition.

import type * as MavenAGI from "../../../../api/index";
import * as core from "../../../../core";
import type * as serializers from "../../../index";
import { Page } from "../../commons/types/Page";
import { AgentUser } from "./AgentUser";

export const AgentUserSearchResponse: core.serialization.ObjectSchema<
    serializers.AgentUserSearchResponse.Raw,
    MavenAGI.AgentUserSearchResponse
> = core.serialization
    .object({
        agentUsers: core.serialization.list(AgentUser),
    })
    .extend(Page);

export declare namespace AgentUserSearchResponse {
    export interface Raw extends Page.Raw {
        agentUsers: AgentUser.Raw[];
    }
}
