// This file was auto-generated by Fern from our API Definition.

import type * as MavenAGI from "../../../index";

/**
 * @example
 *     {
 *         userId: {
 *             referenceId: "user0"
 *         },
 *         agentUserId: "aus_1234567890",
 *         userIdentifiers: [{
 *                 value: "joe@joe.com",
 *                 type: MavenAGI.AppUserIdentifyingPropertyType.Email
 *             }],
 *         allUserData: {
 *             "myapp": {
 *                 "name": "Joe"
 *             }
 *         },
 *         defaultUserData: {
 *             "name": "Joe"
 *         },
 *         agentUserData: {
 *             "name": [{
 *                     value: "Joe",
 *                     visibility: MavenAGI.VisibilityType.Visible,
 *                     userId: {
 *                         appId: "myapp",
 *                         referenceId: "user0"
 *                     }
 *                 }]
 *         }
 *     }
 */
export interface ActionUser {
    /** A user ID that can be used to store user information. Will only be undefined on legacy surfaces. */
    userId?: MavenAGI.EntityIdBase;
    /** The ID of the agent user that the userId is associated with */
    agentUserId?: string;
    /** All known identifiers for the user who is executing the action. */
    userIdentifiers: MavenAGI.AppUserIdentifier[];
    /** Data from all apps */
    allUserData: Record<string, Record<string, string>>;
    /** Default data for this user */
    defaultUserData: Record<string, string>;
    /** All user data for this user, including reverse indexable user data */
    agentUserData: Record<string, MavenAGI.UserDataWithReference[]>;
}
