/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as MavenAGI from "../../../index";

export interface ActionParameter {
    /** The ID field will be used when parameters are supplied to `executeAction`. */
    id: string;
    /** The title of the field that will be shown on action forms. */
    label: string;
    /** A longer description of the field which will be shown in smaller text near the label on action forms. */
    description: string;
    /** Whether the field is required for action execution. */
    required: boolean;
    /** The parameter type. Values provided to `executeAction` will conform to this type. Defaults to `STRING`. */
    type?: MavenAGI.ActionParameterType;
    /** Restricts the action parameter to only the options in this list. Valid for type `STRING`, `BOOLEAN`, and `NUMBER`. */
    enumOptions?: MavenAGI.ActionEnumOption[];
}
