// This file was auto-generated by Fern from our API Definition.

import type * as MavenAGI from "../../../index";

export interface ActionBase extends MavenAGI.ActionProperties {
    /** The name of the action. This is displayed to the end user as part of forms when user interaction is required. It is also used to help Maven decide if the action is relevant to a conversation. */
    name: string;
    /** The description of the action. Must be less than 1024 characters. This helps Maven decide if the action is relevant to a conversation and is not displayed directly to the end user. Descriptions are used by the LLM. */
    description: string;
}
