/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as MavenAGI from "../../../index";

export interface AppUserIdentifyingProperty {
    /** The identifying property text */
    value: string;
    userIdentifyingPropertyType: MavenAGI.AppUserIdentifyingPropertyType;
}
