/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type AttachmentStatus = "PENDING" | "PROCESSING" | "ACCEPTED" | "REJECTED";
export const AttachmentStatus = {
    Pending: "PENDING",
    Processing: "PROCESSING",
    Accepted: "ACCEPTED",
    Rejected: "REJECTED",
} as const;
