// This file was auto-generated by Fern from our API Definition.

/**
 * Pagination parameters for endpoints traversed by an opaque cursor rather than by page offset.
 * Defined as a sibling of BasePaginatedRequest, not a subtype: a cursor traversal has no page
 * number, and offering `page` alongside `cursor` would let a caller send a self-contradictory
 * request. The 200 ceiling is tighter than either offset variant because cursor traversal is
 * designed to walk a whole result set in many small pages.
 */
export interface BaseCursorRequest {
    /** The size of the page to return, defaults to 20. Max 200. */
    size?: number;
    /** Whether to sort descending, defaults to true */
    sortDesc?: boolean;
    /**
     * Opaque cursor from the previous response's `nextCursor`, passed back unchanged. Omit it to
     * start a new traversal. Every other field must stay identical for the whole traversal;
     * changing one is rejected rather than silently restarting from the beginning. Cursors have
     * no expiry, but a cursor can still be rejected with a 400 if the server's signing key has
     * since been rotated out; if that happens, discard it and restart the traversal.
     */
    cursor?: string;
}
