// This file was auto-generated by Fern from our API Definition.

/**
 * Condition for boolean values
 */
export interface BooleanCondition {
    /** The expected boolean value (true or false) */
    value: boolean;
}
