/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * A structured object generated by the bot in response to a schema-based generateObject request. Should be rendered as JSON.
 */
export interface BotObjectResponse {
    /** A human-readable name for the generated object, for use in the UI. */
    label?: string;
    /** The generated object conforming to the provided schema. */
    object?: unknown;
}
