/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as MavenAGI from "../../../index";

export type ConversationPrecondition =
    | MavenAGI.ConversationPrecondition.Tags
    | MavenAGI.ConversationPrecondition.Metadata
    | MavenAGI.ConversationPrecondition.ActionExecuted
    | MavenAGI.ConversationPrecondition.ResponseConfig;

export namespace ConversationPrecondition {
    export interface Tags extends MavenAGI.TagsPrecondition {
        conversationPreconditionType: "tags";
    }

    export interface Metadata extends MavenAGI.MetadataPrecondition {
        conversationPreconditionType: "metadata";
    }

    export interface ActionExecuted extends MavenAGI.ConversationExecutedActionPrecondition {
        conversationPreconditionType: "actionExecuted";
    }

    export interface ResponseConfig extends MavenAGI.ResponseConfigPrecondition {
        conversationPreconditionType: "responseConfig";
    }
}
