// This file was auto-generated by Fern from our API Definition.

import type * as MavenAGI from "../../../index";

export type ConversationMessageResponse =
    | MavenAGI.ConversationMessageResponse.User
    | MavenAGI.ConversationMessageResponse.Bot;

export namespace ConversationMessageResponse {
    export interface User extends MavenAGI.UserMessage {
        type: "user";
    }

    export interface Bot extends MavenAGI.BotMessage {
        type: "bot";
    }
}
