// This file was auto-generated by Fern from our API Definition.

import type * as MavenAGI from "../../../index";

export type ConversationPrecondition =
    | MavenAGI.ConversationPrecondition.Tags
    | MavenAGI.ConversationPrecondition.Metadata
    | MavenAGI.ConversationPrecondition.ActionExecuted
    | MavenAGI.ConversationPrecondition.ResponseConfig
    | MavenAGI.ConversationPrecondition.App
    | MavenAGI.ConversationPrecondition.IntelligentField;

export namespace ConversationPrecondition {
    export interface Tags extends MavenAGI.TagsPrecondition {
        conversationPreconditionType: "tags";
    }

    export interface Metadata extends MavenAGI.MetadataPrecondition {
        conversationPreconditionType: "metadata";
    }

    export interface ActionExecuted extends MavenAGI.ConversationExecutedActionPrecondition {
        conversationPreconditionType: "actionExecuted";
    }

    export interface ResponseConfig extends MavenAGI.ResponseConfigPrecondition {
        conversationPreconditionType: "responseConfig";
    }

    export interface App extends MavenAGI.AppPrecondition {
        conversationPreconditionType: "app";
    }

    export interface IntelligentField extends MavenAGI.IntelligentFieldPrecondition {
        conversationPreconditionType: "intelligentField";
    }
}
