// This file was auto-generated by Fern from our API Definition.

export interface CsatInfo {
    /** The rating of the CSAT rating (0.0, 5.0] */
    rating?: number;
    /** The max rating of the CSAT value (default 5) */
    maxRating?: number;
}
