// This file was auto-generated by Fern from our API Definition.

/** Why a request was rejected. Values are UPPER_SNAKE_CASE, at most 63 characters. New values may be added, so treat an unrecognized one as a generic error. All current values come from agent-variant operations. */
export const ErrorReason = {
    /**
     * The variant is receiving live traffic, so it can't be edited. Fork a working variant and edit that instead. */
    VariantLive: "VARIANT_LIVE",
    /**
     * The variant is archived or deleted. */
    VariantNotActive: "VARIANT_NOT_ACTIVE",
    /**
     * The traffic config changed since it was last read. Re-read it and retry. */
    StaleTrafficRevision: "STALE_TRAFFIC_REVISION",
    /**
     * The variant's working set changed since it was last read (its `workingSetRevision` moved). Re-read it and retry. */
    StaleWorkingSet: "STALE_WORKING_SET",
    /**
     * The variant's staged edits don't change its configuration, so there is nothing to commit. */
    NothingToCommit: "NOTHING_TO_COMMIT",
    /**
     * The ID requested for a new variant is already taken. */
    VariantAlreadyExists: "VARIANT_ALREADY_EXISTS",
    /**
     * The variant is receiving live traffic, so it can't be archived or deleted. Move its traffic elsewhere first. */
    CannotArchiveLiveVariant: "CANNOT_ARCHIVE_LIVE_VARIANT",
    /**
     * A traffic rule, a simulation or an eval run names a variant with staged edits. Publish or discard them first. */
    VariantHasStagedEdits: "VARIANT_HAS_STAGED_EDITS",
    /**
     * The entity type is versioned on this agent, so the request must name the agent variant to read or write. Pass the variant's reference ID, and its owning app where the endpoint takes one; a request that names none is rejected. */
    VariantRequired: "VARIANT_REQUIRED",
    /**
     * The write would change an intelligent field's `validationType` in an agent variant. A field keeps its type across variants; to use a different type, create a new field. */
    IntelligentFieldTypeChanged: "INTELLIGENT_FIELD_TYPE_CHANGED",
} as const;
export type ErrorReason = (typeof ErrorReason)[keyof typeof ErrorReason] | string;
