// This file was auto-generated by Fern from our API Definition.

import type * as MavenAGI from "../../../index";

/**
 * Combines event conditions with a logical operator. Groups nest, so `(a AND b) OR c` is a
 * group holding a group and a condition.
 */
export interface EventConditionGroup {
    /** How to combine `conditions`. */
    operator: MavenAGI.PreconditionGroupOperator;
    /** The conditions to combine. At least one is required; to match every event, omit the trigger's condition entirely. */
    conditions: MavenAGI.EventCondition[];
}
