// This file was auto-generated by Fern from our API Definition.

import type * as MavenAGI from "../../../index";

export interface EventFilter {
    search?: string;
    createdAfter?: Date;
    createdBefore?: Date;
    references?: MavenAGI.ScopedEntity[];
    eventTypes?: MavenAGI.EventType[];
    userEventNames?: MavenAGI.UserEventName[];
    systemEventNames?: MavenAGI.SystemEventName[];
    agentUserIds?: string[];
    legacyFeedbackTypes?: MavenAGI.FeedbackType[];
    hasEventText?: boolean;
}
