// This file was auto-generated by Fern from our API Definition.

export const InboxItemType = {
    /**
     * The inbox item is a duplicate document. */
    DuplicateDocument: "DUPLICATE_DOCUMENT",
    /**
     * The inbox item is missing knowledge. */
    MissingKnowledge: "MISSING_KNOWLEDGE",
    /**
     * The inbox item is a custom api-provided inbox item. */
    Custom: "CUSTOM",
} as const;
export type InboxItemType = (typeof InboxItemType)[keyof typeof InboxItemType];
