/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as MavenAGI from "../../../index";

export interface InboxItemFixDeactivateKnowledgeBase extends MavenAGI.InboxItemFixBase {
    /** The knowledge base associated with this fix. */
    knowledgeBase: MavenAGI.KnowledgeBaseInformation;
}
