// This file was auto-generated by Fern from our API Definition.

import type * as MavenAGI from "../../../index";

/**
 * The condition to evaluate against an intelligent field's value.
 * Use the appropriate type based on the field's validationType:
 * - `string`: For STRING and MULTILINE fields
 * - `numeric`: For NUMBER fields
 * - `boolean`: For BOOLEAN fields
 * - `set`: For MULTI_SELECT fields (unordered set of values)
 *
 * Note: single select fields are represented as STRING/NUMBER with a list of
 * enumOptions.
 *
 * The caller is responsible for querying the validationType and enumOptions
 * from the intelligent field API to ensure the values are valid enumOptions.
 */
export type IntelligentFieldCondition =
    | MavenAGI.IntelligentFieldCondition.String
    | MavenAGI.IntelligentFieldCondition.Numeric
    | MavenAGI.IntelligentFieldCondition.Boolean
    | MavenAGI.IntelligentFieldCondition.Set;

export namespace IntelligentFieldCondition {
    export interface String {
        fieldValidationType: "string";
        value: MavenAGI.StringCondition;
    }

    export interface Numeric {
        fieldValidationType: "numeric";
        value: MavenAGI.NumericCondition;
    }

    export interface Boolean extends MavenAGI.BooleanCondition {
        fieldValidationType: "boolean";
    }

    export interface Set {
        fieldValidationType: "set";
        value: MavenAGI.SetCondition;
    }
}
