// This file was auto-generated by Fern from our API Definition.

import type * as MavenAGI from "../../../index";

/**
 * A precondition based on the computed value of an intelligent field on the conversation.
 *
 * The structure of this precondition follows `LHS OP RHS`, where the LHS is
 * the ID of the intelligent field (<referenceId, appId>).  Available
 * operators and the corresponding types of the RHS depends on the
 * validationType of the intelligent field.
 */
export interface IntelligentFieldPrecondition {
    /** The ID of the intelligent field. */
    fieldIdWithoutAgent: MavenAGI.EntityIdWithoutAgent;
    /** The condition to evaluate against the field's value. */
    fieldCondition: MavenAGI.FieldCondition;
}
