/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as MavenAGI from "../../../index";

export interface KnowledgeBaseInformation {
    /** Unique identifier for the knowledge base. */
    knowledgeBaseId: MavenAGI.EntityIdWithoutAgent;
}
