// This file was auto-generated by Fern from our API Definition.

export const LlmInclusionStatus = {
    Always: "ALWAYS",
    WhenRelevant: "WHEN_RELEVANT",
    Never: "NEVER",
} as const;
export type LlmInclusionStatus = (typeof LlmInclusionStatus)[keyof typeof LlmInclusionStatus];
