/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type LlmInclusionStatus = "ALWAYS" | "WHEN_RELEVANT" | "NEVER";
export const LlmInclusionStatus = {
    Always: "ALWAYS",
    WhenRelevant: "WHEN_RELEVANT",
    Never: "NEVER",
} as const;
