// This file was auto-generated by Fern from our API Definition.

export const LlmPersona = {
    CasualBuddy: "CASUAL_BUDDY",
    EmpatheticSupporter: "EMPATHETIC_SUPPORTER",
    FormalProfessional: "FORMAL_PROFESSIONAL",
    ConciseExpert: "CONCISE_EXPERT",
    EnthusiasticHelper: "ENTHUSIASTIC_HELPER",
    PatientEducator: "PATIENT_EDUCATOR",
    Pirate: "PIRATE",
} as const;
export type LlmPersona = (typeof LlmPersona)[keyof typeof LlmPersona];
