// This file was auto-generated by Fern from our API Definition.

import type * as MavenAGI from "../../../index";

export interface NovelUserEvent extends MavenAGI.EventBaseNoId {
    /** The unique ID of the event */
    id: MavenAGI.EntityIdBase;
    /** The name of the event */
    eventName: MavenAGI.UserEventName;
    /** Information about the user who triggered the event */
    userInfo: MavenAGI.EventUserInfoBase;
    /** Information about any CSAT associated with the event */
    csatInfo?: MavenAGI.CsatInfo;
    /** Information about any feedback associated with the event */
    feedbackInfo?: MavenAGI.FeedbackInfo[];
    /** Information about the page on which the event occurred */
    pageInfo?: MavenAGI.PageInfo;
}
