// This file was auto-generated by Fern from our API Definition.

import type * as MavenAGI from "../../../index";

/**
 * Condition checking membership in a set of numbers
 */
export interface NumericMembershipCondition {
    /** The comparison operator to apply */
    operator: MavenAGI.NumericMembershipOperator;
    /** The set of numeric values to compare against */
    values: number[];
}
