// This file was auto-generated by Fern from our API Definition.

/**
 * Type-independent operators that check whether an intelligent field has a
 * determined value on the conversation, rather than comparing its value.
 */
export const PresenceOperator = {
    /**
     * The field has no determined value — the LLM could not determine one, the
     * computation failed, is still running, or has not run. Surfaced to authors as
     * the special "Undetermined" value. */
    IsUndetermined: "IS_UNDETERMINED",
    /**
     * The field has a determined (non-null) value. */
    IsDetermined: "IS_DETERMINED",
} as const;
export type PresenceOperator = (typeof PresenceOperator)[keyof typeof PresenceOperator] | string;
