// This file was auto-generated by Fern from our API Definition.

/**
 * The kind of relationship (edge) between two entities. Names the edge,
 * not the node — `EntityId` already carries the node type.
 *
 * * `SPAWN_FROM`: the entity this one was spawned from.
 * * `SPAWN_TO`: the entities that were spawned from this one.
 */
export const RelationshipType = {
    SpawnFrom: "SPAWN_FROM",
    SpawnTo: "SPAWN_TO",
} as const;
export type RelationshipType = (typeof RelationshipType)[keyof typeof RelationshipType] | string;
