// This file was auto-generated by Fern from our API Definition.

import type * as MavenAGI from "../../../index";

export interface ResponseConfigPrecondition extends MavenAGI.PreconditionBase {
    useMarkdown?: boolean;
    useForms?: boolean;
    useImages?: boolean;
    isCopilot?: boolean;
    responseLength?: MavenAGI.ResponseLength;
}
