// This file was auto-generated by Fern from our API Definition.

import type * as MavenAGI from "../../../index";

/**
 * Condition comparing against a single string value
 */
export interface StringComparisonCondition {
    /** The comparison operator to apply */
    operator: MavenAGI.StringComparisonOperator;
    /** The string value to compare against */
    value: string;
}
