// This file was auto-generated by Fern from our API Definition.

import type * as MavenAGI from "../../../index";

/**
 * Condition checking membership in a set of strings
 */
export interface StringMembershipCondition {
    /** The comparison operator to apply */
    operator: MavenAGI.StringMembershipOperator;
    /** The set of string values to compare against */
    values: string[];
}
