// This file was auto-generated by Fern from our API Definition.

export const SystemEventName = {
    /**
     * An app was installed */
    AppInstalled: "APP_INSTALLED",
    /**
     * An app was uninstalled */
    AppUninstalled: "APP_UNINSTALLED",
    /**
     * An app was updated */
    AppUpdated: "APP_UPDATED",
    /**
     * An outbound notification was sent to a user */
    NotificationSent: "NOTIFICATION_SENT",
    /**
     * An outbound notification reached the user */
    NotificationDelivered: "NOTIFICATION_DELIVERED",
    /**
     * An outbound notification could not be delivered */
    NotificationFailed: "NOTIFICATION_FAILED",
    /**
     * An external system was connected */
    IntegrationConnected: "INTEGRATION_CONNECTED",
    /**
     * An external system was disconnected */
    IntegrationDisconnected: "INTEGRATION_DISCONNECTED",
    /**
     * A data sync with an external system began */
    SyncStarted: "SYNC_STARTED",
    /**
     * A data sync with an external system finished */
    SyncCompleted: "SYNC_COMPLETED",
    /**
     * A data sync with an external system failed */
    SyncFailed: "SYNC_FAILED",
    /**
     * An intelligent field's value on a conversation was set or changed. `references` carries the conversation and the field; `contextInfo.additionalData` carries `fieldReferenceId`, `fieldAppId`, the new `value` and the `previousValue`, both as JSON strings. An undetermined value is the JSON string `null` on either key. `previousValue` is absent only when the field was set for the first time and had no previous value at all. */
    IntelligentFieldValueChanged: "INTELLIGENT_FIELD_VALUE_CHANGED",
} as const;
export type SystemEventName = (typeof SystemEventName)[keyof typeof SystemEventName] | string;
