// This file was auto-generated by Fern from our API Definition.

import type * as MavenAGI from "../../../index";

/**
 * Type-independent conditions that apply to any intelligent field regardless of its
 * validationType. Currently only a presence (determined/undetermined) check. Modeled as
 * its own discriminated union so future type-independent operators can be added without
 * changing the top-level IntelligentFieldCondition union.
 */
export type UniversalCondition = MavenAGI.UniversalCondition.Presence;

export namespace UniversalCondition {
    export interface Presence extends MavenAGI.PresenceCondition {
        opType: "presence";
    }
}
