// This file was auto-generated by Fern from our API Definition.

import * as MavenAGI from "../../../index";

export interface UserDataWithReference extends MavenAGI.UserData {
    /** Reverse index containing appId and referenceId data that identifies this app user */
    userId: MavenAGI.EntityIdFilter;
}
