/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as environments from "./environments";
import * as core from "./core";
import { Actions } from "./api/resources/actions/client/Client";
import { AppSettings } from "./api/resources/appSettings/client/Client";
import { Conversation } from "./api/resources/conversation/client/Client";
import { Knowledge } from "./api/resources/knowledge/client/Client";
import { Triggers } from "./api/resources/triggers/client/Client";
import { Users } from "./api/resources/users/client/Client";

export declare namespace MavenAGIClient {
    interface Options {
        environment?: core.Supplier<environments.MavenAGIEnvironment | string>;
        appId?: core.Supplier<string | undefined>;
        appSecret?: core.Supplier<string | undefined>;
        /** Override the X-Organization-Id header */
        organizationId: core.Supplier<string>;
        /** Override the X-Agent-Id header */
        agentId: core.Supplier<string>;
        fetcher?: core.FetchFunction;
    }

    interface RequestOptions {
        /** The maximum time to wait for a response in seconds. */
        timeoutInSeconds?: number;
        /** The number of times to retry the request. Defaults to 2. */
        maxRetries?: number;
        /** A hook to abort the request. */
        abortSignal?: AbortSignal;
        /** Override the X-Organization-Id header */
        organizationId?: string;
        /** Override the X-Agent-Id header */
        agentId?: string;
    }
}

export class MavenAGIClient {
    constructor(protected readonly _options: MavenAGIClient.Options) {}

    protected _actions: Actions | undefined;

    public get actions(): Actions {
        return (this._actions ??= new Actions(this._options));
    }

    protected _appSettings: AppSettings | undefined;

    public get appSettings(): AppSettings {
        return (this._appSettings ??= new AppSettings(this._options));
    }

    protected _conversation: Conversation | undefined;

    public get conversation(): Conversation {
        return (this._conversation ??= new Conversation(this._options));
    }

    protected _knowledge: Knowledge | undefined;

    public get knowledge(): Knowledge {
        return (this._knowledge ??= new Knowledge(this._options));
    }

    protected _triggers: Triggers | undefined;

    public get triggers(): Triggers {
        return (this._triggers ??= new Triggers(this._options));
    }

    protected _users: Users | undefined;

    public get users(): Users {
        return (this._users ??= new Users(this._options));
    }
}
