// This file was auto-generated by Fern from our API Definition.

export const MavenAGIEnvironment = {
    Production: "https://www.mavenagi-apis.com",
    Staging: "https://www.staging.mavenagi-apis.com",
} as const;

export type MavenAGIEnvironment = typeof MavenAGIEnvironment.Production | typeof MavenAGIEnvironment.Staging;
