// This file was auto-generated by Fern from our API Definition.

import type * as MavenAGI from "../../../index";

export interface UpdateIntegrationRequest {
    settingsSchema?: MavenAGI.SettingsSchema;
    githubRepository?: MavenAGI.GithubRepository | null;
    githubBranch?: string | null;
    visibility?: MavenAGI.AppVisibility;
    developerOrganizationId?: string;
    name?: string;
    description?: string | null;
    shortDescription?: string | null;
    installationInstructions?: string | null;
    instructions?: string | null;
    previewUrl?: string | null;
    links?: MavenAGI.Link[];
    categories?: MavenAGI.AppCategory[];
    capabilities?: MavenAGI.AppCapability[];
    preinstalled?: boolean;
    whitelistedOrganizations?: string[];
    requestedPermissions?: string[];
}
