/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as MavenAGI from "../../../../api/index";
import * as core from "../../../../core";
import { AppSettings } from "./AppSettings";

export const SearchAppSettingsResponse: core.serialization.ObjectSchema<
    serializers.SearchAppSettingsResponse.Raw,
    MavenAGI.SearchAppSettingsResponse
> = core.serialization.object({
    results: core.serialization.list(AppSettings),
});

export declare namespace SearchAppSettingsResponse {
    export interface Raw {
        results: AppSettings.Raw[];
    }
}
