// This file was auto-generated by Fern from our API Definition.

export const KnowledgeBaseRefreshFrequency = {
    None: "NONE",
    Daily: "DAILY",
    Weekly: "WEEKLY",
    Monthly: "MONTHLY",
} as const;
export type KnowledgeBaseRefreshFrequency =
    (typeof KnowledgeBaseRefreshFrequency)[keyof typeof KnowledgeBaseRefreshFrequency];
