/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as MavenAGI from "../../../index";

export interface KnowledgeBasePatchRequest {
    /** The App ID of the knowledge base to patch. If not provided the ID of the calling app will be used. */
    appId?: string;
    /** The name of the knowledge base. */
    name?: string;
    /** The tags of the knowledge base. */
    tags?: Set<string>;
    /** Determines whether documents in the knowledge base are sent to the LLM as part of a conversation. Note that at this time knowledge bases can not be set to `ALWAYS`. */
    llmInclusionStatus?: MavenAGI.LlmInclusionStatus;
    /** How often the knowledge base should be refreshed. */
    refreshFrequency?: MavenAGI.KnowledgeBaseRefreshFrequency;
}
