// This file was auto-generated by Fern from our API Definition.

export const KnowledgeDocumentField = {
    Title: "Title",
    CreatedAt: "CreatedAt",
    UpdatedAt: "UpdatedAt",
    Language: "Language",
} as const;
export type KnowledgeDocumentField = (typeof KnowledgeDocumentField)[keyof typeof KnowledgeDocumentField];
