/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type KnowledgeBaseField = "Title" | "UpdatedAt";
export const KnowledgeBaseField = {
    Title: "Title",
    UpdatedAt: "UpdatedAt",
} as const;
