// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         contentLength: 1,
 *         contentType: "contentType"
 *     }
 */
export interface GetAppSettingUploadUrlRequest {
    contentLength: number;
    contentType: string;
}
