/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as MavenAGI from "../../../../api/index";
import * as core from "../../../../core";

export const ActionEnumOption: core.serialization.ObjectSchema<
    serializers.ActionEnumOption.Raw,
    MavenAGI.ActionEnumOption
> = core.serialization.object({
    label: core.serialization.string(),
    value: core.serialization.unknown(),
});

export declare namespace ActionEnumOption {
    export interface Raw {
        label: string;
        value?: unknown;
    }
}
