// This file was auto-generated by Fern from our API Definition.

import type * as MavenAGI from "../../../../api/index";
import * as core from "../../../../core";
import type * as serializers from "../../../index";

export const AdditionalDataKey: core.serialization.Schema<
    serializers.AdditionalDataKey.Raw,
    MavenAGI.AdditionalDataKey
> = core.serialization.forwardCompatibleEnum_([
    "value",
    "previousValue",
    "name",
    "step",
    "reason",
    "errorCode",
    "errorMessage",
    "url",
    "query",
    "position",
    "amount",
    "currency",
    "channel",
    "sourceLanguage",
    "targetLanguage",
    "mimeType",
    "sizeBytes",
]);

export declare namespace AdditionalDataKey {
    export type Raw =
        | "value"
        | "previousValue"
        | "name"
        | "step"
        | "reason"
        | "errorCode"
        | "errorMessage"
        | "url"
        | "query"
        | "position"
        | "amount"
        | "currency"
        | "channel"
        | "sourceLanguage"
        | "targetLanguage"
        | "mimeType"
        | "sizeBytes";
}
