/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as MavenAGI from "../../../../api/index";
import * as core from "../../../../core";
import { AppUserIdentifyingProperty } from "./AppUserIdentifyingProperty";

export const AppUserIdentification: core.serialization.ObjectSchema<
    serializers.AppUserIdentification.Raw,
    MavenAGI.AppUserIdentification
> = core.serialization.object({
    identifiers: core.serialization.list(AppUserIdentifyingProperty),
});

export declare namespace AppUserIdentification {
    interface Raw {
        identifiers: AppUserIdentifyingProperty.Raw[];
    }
}
