// This file was auto-generated by Fern from our API Definition.

import * as serializers from "../../../index";
import * as MavenAGI from "../../../../api/index";
import * as core from "../../../../core";

export const AppUserIdentifyingPropertyType: core.serialization.Schema<
    serializers.AppUserIdentifyingPropertyType.Raw,
    MavenAGI.AppUserIdentifyingPropertyType
> = core.serialization.enum_(["EMAIL", "PHONE_NUMBER"]);

export declare namespace AppUserIdentifyingPropertyType {
    export type Raw = "EMAIL" | "PHONE_NUMBER";
}
