// This file was auto-generated by Fern from our API Definition.

import type * as MavenAGI from "../../../../api/index";
import * as core from "../../../../core";
import type * as serializers from "../../../index";

export const BaseCursorRequest: core.serialization.ObjectSchema<
    serializers.BaseCursorRequest.Raw,
    MavenAGI.BaseCursorRequest
> = core.serialization.object({
    size: core.serialization.number().optional(),
    sortDesc: core.serialization.boolean().optional(),
    cursor: core.serialization.string().optional(),
});

export declare namespace BaseCursorRequest {
    export interface Raw {
        size?: number | null;
        sortDesc?: boolean | null;
        cursor?: string | null;
    }
}
