// This file was auto-generated by Fern from our API Definition.

import type * as MavenAGI from "../../../../api/index";
import * as core from "../../../../core";
import type * as serializers from "../../../index";

export const BooleanCondition: core.serialization.ObjectSchema<
    serializers.BooleanCondition.Raw,
    MavenAGI.BooleanCondition
> = core.serialization.object({
    value: core.serialization.boolean(),
});

export declare namespace BooleanCondition {
    export interface Raw {
        value: boolean;
    }
}
