// This file was auto-generated by Fern from our API Definition.

import * as serializers from "../../../index";
import * as MavenAGI from "../../../../api/index";
import * as core from "../../../../core";

export const BotLogicUserItem: core.serialization.ObjectSchema<
    serializers.BotLogicUserItem.Raw,
    MavenAGI.BotLogicUserItem
> = core.serialization.object({
    userData: core.serialization.record(core.serialization.string(), core.serialization.string()),
});

export declare namespace BotLogicUserItem {
    export interface Raw {
        userData: Record<string, string>;
    }
}
