/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as MavenAGI from "../../../../api/index";
import * as core from "../../../../core";
import { EntityId } from "./EntityId";

export const BotLogicSegmentsItem: core.serialization.ObjectSchema<
    serializers.BotLogicSegmentsItem.Raw,
    MavenAGI.BotLogicSegmentsItem
> = core.serialization.object({
    matchingSegmentIds: core.serialization.list(EntityId),
});

export declare namespace BotLogicSegmentsItem {
    export interface Raw {
        matchingSegmentIds: EntityId.Raw[];
    }
}
