// This file was auto-generated by Fern from our API Definition.

import type * as MavenAGI from "../../../../api/index";
import * as core from "../../../../core";
import type * as serializers from "../../../index";
import { BotLogicKnowledgeDetail } from "./BotLogicKnowledgeDetail";

export const BotLogicKnowledgeItem: core.serialization.ObjectSchema<
    serializers.BotLogicKnowledgeItem.Raw,
    MavenAGI.BotLogicKnowledgeItem
> = core.serialization.object({
    knowledgeReviewed: core.serialization.list(BotLogicKnowledgeDetail),
    knowledgeUtilized: core.serialization.list(BotLogicKnowledgeDetail),
});

export declare namespace BotLogicKnowledgeItem {
    export interface Raw {
        knowledgeReviewed: BotLogicKnowledgeDetail.Raw[];
        knowledgeUtilized: BotLogicKnowledgeDetail.Raw[];
    }
}
