// This file was auto-generated by Fern from our API Definition.

import * as serializers from "../../../index";
import * as MavenAGI from "../../../../api/index";
import * as core from "../../../../core";
import { EntityIdWithoutAgent } from "./EntityIdWithoutAgent";

export const BotLogicKnowledgeDetail: core.serialization.ObjectSchema<
    serializers.BotLogicKnowledgeDetail.Raw,
    MavenAGI.BotLogicKnowledgeDetail
> = core.serialization.object({
    knowledgeBaseId: EntityIdWithoutAgent,
    documentId: EntityIdWithoutAgent,
    documentName: core.serialization.string(),
    documentExcerpt: core.serialization.string(),
});

export declare namespace BotLogicKnowledgeDetail {
    export interface Raw {
        knowledgeBaseId: EntityIdWithoutAgent.Raw;
        documentId: EntityIdWithoutAgent.Raw;
        documentName: string;
        documentExcerpt: string;
    }
}
