/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as MavenAGI from "../../../../api/index";
import * as core from "../../../../core";

export const BotMessageStatus: core.serialization.Schema<serializers.BotMessageStatus.Raw, MavenAGI.BotMessageStatus> =
    core.serialization.enum_(["SENDING", "SENT", "REJECTED", "CANCELED", "FAILED", "UNKNOWN"]);

export declare namespace BotMessageStatus {
    export type Raw = "SENDING" | "SENT" | "REJECTED" | "CANCELED" | "FAILED" | "UNKNOWN";
}
