// This file was auto-generated by Fern from our API Definition.

import type * as MavenAGI from "../../../../api/index";
import * as core from "../../../../core";
import type * as serializers from "../../../index";
import { BotConversationMessageType } from "./BotConversationMessageType";
import { BotLogic } from "./BotLogic";
import { BotResponse } from "./BotResponse";
import { BotResponseMetadata } from "./BotResponseMetadata";
import { ConversationMessageBase } from "./ConversationMessageBase";
import { EntityId } from "./EntityId";
import { MessageStatus } from "./MessageStatus";

export const BotMessage: core.serialization.ObjectSchema<serializers.BotMessage.Raw, MavenAGI.BotMessage> =
    core.serialization
        .object({
            conversationMessageId: EntityId,
            botMessageType: BotConversationMessageType,
            responses: core.serialization.list(BotResponse),
            metadata: BotResponseMetadata,
            status: MessageStatus,
            logic: BotLogic.optional(),
        })
        .extend(ConversationMessageBase);

export declare namespace BotMessage {
    export interface Raw extends ConversationMessageBase.Raw {
        conversationMessageId: EntityId.Raw;
        botMessageType: BotConversationMessageType.Raw;
        responses: BotResponse.Raw[];
        metadata: BotResponseMetadata.Raw;
        status: MessageStatus.Raw;
        logic?: BotLogic.Raw | null;
    }
}
