// This file was auto-generated by Fern from our API Definition.

import type * as MavenAGI from "../../../../api/index";
import * as core from "../../../../core";
import type * as serializers from "../../../index";

export const ChartSpecSchema: core.serialization.Schema<serializers.ChartSpecSchema.Raw, MavenAGI.ChartSpecSchema> =
    core.serialization.enum_(["HIGHCHARTS_TS"]);

export declare namespace ChartSpecSchema {
    export type Raw = "HIGHCHARTS_TS";
}
