/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as MavenAGI from "../../../../api/index";
import * as core from "../../../../core";
import { Sentiment } from "./Sentiment";
import { Quality } from "./Quality";
import { QualityReason } from "./QualityReason";

export const ConversationAnalysis: core.serialization.ObjectSchema<
    serializers.ConversationAnalysis.Raw,
    MavenAGI.ConversationAnalysis
> = core.serialization.object({
    userRequest: core.serialization.string().optional(),
    agentResponse: core.serialization.string().optional(),
    resolutionStatus: core.serialization.string().optional(),
    category: core.serialization.string().optional(),
    sentiment: Sentiment.optional(),
    quality: Quality.optional(),
    qualityReason: QualityReason.optional(),
    resolvedByMaven: core.serialization.boolean().optional(),
    primaryLanguage: core.serialization.string().optional(),
});

export declare namespace ConversationAnalysis {
    export interface Raw {
        userRequest?: string | null;
        agentResponse?: string | null;
        resolutionStatus?: string | null;
        category?: string | null;
        sentiment?: Sentiment.Raw | null;
        quality?: Quality.Raw | null;
        qualityReason?: QualityReason.Raw | null;
        resolvedByMaven?: boolean | null;
        primaryLanguage?: string | null;
    }
}
