// This file was auto-generated by Fern from our API Definition.

import type * as MavenAGI from "../../../../api/index";
import * as core from "../../../../core";
import type * as serializers from "../../../index";
import { AttachmentResponse } from "./AttachmentResponse";
import { BaseConversationResponse } from "./BaseConversationResponse";
import { ConversationMessageResponse } from "./ConversationMessageResponse";

export const ConversationResponse: core.serialization.ObjectSchema<
    serializers.ConversationResponse.Raw,
    MavenAGI.ConversationResponse
> = core.serialization
    .object({
        messages: core.serialization.list(ConversationMessageResponse),
        attachments: core.serialization.list(AttachmentResponse),
    })
    .extend(BaseConversationResponse);

export declare namespace ConversationResponse {
    export interface Raw extends BaseConversationResponse.Raw {
        messages: ConversationMessageResponse.Raw[];
        attachments: AttachmentResponse.Raw[];
    }
}
