// This file was auto-generated by Fern from our API Definition.

import type * as MavenAGI from "../../../../api/index";
import * as core from "../../../../core";
import type * as serializers from "../../../index";
import { SettingsSchemaEntryBase } from "./SettingsSchemaEntryBase";

export const DropdownSettingsSchemaEntry: core.serialization.ObjectSchema<
    serializers.DropdownSettingsSchemaEntry.Raw,
    MavenAGI.DropdownSettingsSchemaEntry
> = core.serialization
    .object({
        dropdownOptions: core.serialization.list(core.serialization.string()),
        defaultValue: core.serialization.string().optional(),
    })
    .extend(SettingsSchemaEntryBase);

export declare namespace DropdownSettingsSchemaEntry {
    export interface Raw extends SettingsSchemaEntryBase.Raw {
        dropdownOptions: string[];
        defaultValue?: string | null;
    }
}
