// This file was auto-generated by Fern from our API Definition.

import * as serializers from "../../../index";
import * as MavenAGI from "../../../../api/index";
import * as core from "../../../../core";

export const EntityType: core.serialization.Schema<serializers.EntityType.Raw, MavenAGI.EntityType> =
    core.serialization.enum_([
        "AGENT",
        "CONVERSATION",
        "CONVERSATION_MESSAGE",
        "KNOWLEDGE_BASE",
        "KNOWLEDGE_BASE_VERSION",
        "KNOWLEDGE_DOCUMENT",
        "ACTION",
        "USER",
        "EVENT",
        "EVENT_TRIGGER",
        "USER_PROFILE",
        "FEEDBACK",
        "INBOX_ITEM",
        "INBOX_ITEM_FIX",
        "SEGMENT",
        "CUSTOMER",
    ]);

export declare namespace EntityType {
    export type Raw =
        | "AGENT"
        | "CONVERSATION"
        | "CONVERSATION_MESSAGE"
        | "KNOWLEDGE_BASE"
        | "KNOWLEDGE_BASE_VERSION"
        | "KNOWLEDGE_DOCUMENT"
        | "ACTION"
        | "USER"
        | "EVENT"
        | "EVENT_TRIGGER"
        | "USER_PROFILE"
        | "FEEDBACK"
        | "INBOX_ITEM"
        | "INBOX_ITEM_FIX"
        | "SEGMENT"
        | "CUSTOMER";
}
