// This file was auto-generated by Fern from our API Definition.

import type * as MavenAGI from "../../../../api/index";
import * as core from "../../../../core";
import type * as serializers from "../../../index";
import { EventType } from "./EventType";
import { FeedbackType } from "./FeedbackType";
import { ScopedEntity } from "./ScopedEntity";
import { SystemEventName } from "./SystemEventName";
import { UserEventName } from "./UserEventName";

export const EventFilter: core.serialization.ObjectSchema<serializers.EventFilter.Raw, MavenAGI.EventFilter> =
    core.serialization.object({
        search: core.serialization.string().optional(),
        createdAfter: core.serialization.date().optional(),
        createdBefore: core.serialization.date().optional(),
        references: core.serialization.list(ScopedEntity).optional(),
        eventTypes: core.serialization.list(EventType).optional(),
        userEventNames: core.serialization.list(UserEventName).optional(),
        systemEventNames: core.serialization.list(SystemEventName).optional(),
        agentUserIds: core.serialization.list(core.serialization.string()).optional(),
        legacyFeedbackTypes: core.serialization.list(FeedbackType).optional(),
        hasEventText: core.serialization.boolean().optional(),
    });

export declare namespace EventFilter {
    export interface Raw {
        search?: string | null;
        createdAfter?: string | null;
        createdBefore?: string | null;
        references?: ScopedEntity.Raw[] | null;
        eventTypes?: EventType.Raw[] | null;
        userEventNames?: UserEventName.Raw[] | null;
        systemEventNames?: SystemEventName.Raw[] | null;
        agentUserIds?: string[] | null;
        legacyFeedbackTypes?: FeedbackType.Raw[] | null;
        hasEventText?: boolean | null;
    }
}
