// This file was auto-generated by Fern from our API Definition.

import type * as MavenAGI from "../../../../api/index";
import * as core from "../../../../core";
import type * as serializers from "../../../index";
import { BooleanCondition } from "./BooleanCondition";
import { NumericCondition } from "./NumericCondition";
import { SetCondition } from "./SetCondition";
import { StringCondition } from "./StringCondition";
import { UniversalCondition } from "./UniversalCondition";

export const FieldCondition: core.serialization.Schema<serializers.FieldCondition.Raw, MavenAGI.FieldCondition> =
    core.serialization
        .union("fieldValidationType", {
            string: core.serialization.object({
                value: StringCondition,
            }),
            numeric: core.serialization.object({
                value: NumericCondition,
            }),
            boolean: BooleanCondition,
            set: core.serialization.object({
                value: SetCondition,
            }),
            universal: core.serialization.object({
                value: UniversalCondition,
            }),
        })
        .transform<MavenAGI.FieldCondition>({
            transform: (value) => value,
            untransform: (value) => value,
        });

export declare namespace FieldCondition {
    export type Raw =
        | FieldCondition.String
        | FieldCondition.Numeric
        | FieldCondition.Boolean
        | FieldCondition.Set
        | FieldCondition.Universal;

    export interface String {
        fieldValidationType: "string";
        value: StringCondition.Raw;
    }

    export interface Numeric {
        fieldValidationType: "numeric";
        value: NumericCondition.Raw;
    }

    export interface Boolean extends BooleanCondition.Raw {
        fieldValidationType: "boolean";
    }

    export interface Set {
        fieldValidationType: "set";
        value: SetCondition.Raw;
    }

    export interface Universal {
        fieldValidationType: "universal";
        value: UniversalCondition.Raw;
    }
}
