/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as MavenAGI from "../../../../api/index";
import * as core from "../../../../core";
import { DocumentInformation } from "./DocumentInformation";
import { InboxItemFixBase } from "./InboxItemFixBase";

export const InboxItemFixDeactivateDocument: core.serialization.ObjectSchema<
    serializers.InboxItemFixDeactivateDocument.Raw,
    MavenAGI.InboxItemFixDeactivateDocument
> = core.serialization
    .object({
        documentInformation: DocumentInformation,
    })
    .extend(InboxItemFixBase);

export declare namespace InboxItemFixDeactivateDocument {
    export interface Raw extends InboxItemFixBase.Raw {
        documentInformation: DocumentInformation.Raw;
    }
}
