/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as MavenAGI from "../../../../api/index";
import * as core from "../../../../core";
import { InboxItemFixDeactivateDocument } from "./InboxItemFixDeactivateDocument";
import { DocumentInformation } from "./DocumentInformation";
import { InboxItemBase } from "./InboxItemBase";

export const InboxItemDuplicateDocuments: core.serialization.ObjectSchema<
    serializers.InboxItemDuplicateDocuments.Raw,
    MavenAGI.InboxItemDuplicateDocuments
> = core.serialization
    .object({
        recommendedFixes: core.serialization.list(InboxItemFixDeactivateDocument),
        otherFixes: core.serialization.list(InboxItemFixDeactivateDocument),
        documents: core.serialization.list(DocumentInformation),
    })
    .extend(InboxItemBase);

export declare namespace InboxItemDuplicateDocuments {
    export interface Raw extends InboxItemBase.Raw {
        recommendedFixes: InboxItemFixDeactivateDocument.Raw[];
        otherFixes: InboxItemFixDeactivateDocument.Raw[];
        documents: DocumentInformation.Raw[];
    }
}
