// This file was auto-generated by Fern from our API Definition.

import type * as MavenAGI from "../../../../api/index";
import * as core from "../../../../core";
import type * as serializers from "../../../index";
import { InboxItemCustom } from "./InboxItemCustom";
import { InboxItemDuplicateDocuments } from "./InboxItemDuplicateDocuments";
import { InboxItemMissingKnowledge } from "./InboxItemMissingKnowledge";

export const InboxItem: core.serialization.Schema<serializers.InboxItem.Raw, MavenAGI.InboxItem> = core.serialization
    .union("type", {
        duplicateDocuments: InboxItemDuplicateDocuments,
        missingKnowledge: InboxItemMissingKnowledge,
        custom: InboxItemCustom,
    })
    .transform<MavenAGI.InboxItem>({
        transform: (value) => value,
        untransform: (value) => value,
    });

export declare namespace InboxItem {
    export type Raw = InboxItem.DuplicateDocuments | InboxItem.MissingKnowledge | InboxItem.Custom;

    export interface DuplicateDocuments extends InboxItemDuplicateDocuments.Raw {
        type: "duplicateDocuments";
    }

    export interface MissingKnowledge extends InboxItemMissingKnowledge.Raw {
        type: "missingKnowledge";
    }

    export interface Custom extends InboxItemCustom.Raw {
        type: "custom";
    }
}
