// This file was auto-generated by Fern from our API Definition.

import * as serializers from "../../../index";
import * as MavenAGI from "../../../../api/index";
import * as core from "../../../../core";
import { InboxItemFixAddDocument } from "./InboxItemFixAddDocument";
import { ConversationInformation } from "./ConversationInformation";
import { InboxItemBase } from "./InboxItemBase";

export const InboxItemMissingKnowledge: core.serialization.ObjectSchema<
    serializers.InboxItemMissingKnowledge.Raw,
    MavenAGI.InboxItemMissingKnowledge
> = core.serialization
    .object({
        fix: InboxItemFixAddDocument,
        conversations: core.serialization.list(ConversationInformation),
    })
    .extend(InboxItemBase);

export declare namespace InboxItemMissingKnowledge {
    export interface Raw extends InboxItemBase.Raw {
        fix: InboxItemFixAddDocument.Raw;
        conversations: ConversationInformation.Raw[];
    }
}
