// This file was auto-generated by Fern from our API Definition.

import type * as MavenAGI from "../../../../api/index";
import * as core from "../../../../core";
import type * as serializers from "../../../index";
import { IntelligentFieldCondition } from "./IntelligentFieldCondition";

export const IntelligentFieldPrecondition: core.serialization.ObjectSchema<
    serializers.IntelligentFieldPrecondition.Raw,
    MavenAGI.IntelligentFieldPrecondition
> = core.serialization.object({
    fieldReferenceId: core.serialization.string(),
    fieldAppId: core.serialization.string().optional(),
    fieldCondition: IntelligentFieldCondition,
});

export declare namespace IntelligentFieldPrecondition {
    export interface Raw {
        fieldReferenceId: string;
        fieldAppId?: string | null;
        fieldCondition: IntelligentFieldCondition.Raw;
    }
}
