// This file was auto-generated by Fern from our API Definition.

import type * as MavenAGI from "../../../../api/index";
import * as core from "../../../../core";
import type * as serializers from "../../../index";

export const IpInfo: core.serialization.ObjectSchema<serializers.IpInfo.Raw, MavenAGI.IpInfo> =
    core.serialization.object({
        ip: core.serialization.string().optional(),
    });

export declare namespace IpInfo {
    export interface Raw {
        ip?: string | null;
    }
}
