// This file was auto-generated by Fern from our API Definition.

import type * as MavenAGI from "../../../../api/index";
import * as core from "../../../../core";
import type * as serializers from "../../../index";
import { ScopedEntity } from "./ScopedEntity";

export const KnowledgeContextByEntities: core.serialization.ObjectSchema<
    serializers.KnowledgeContextByEntities.Raw,
    MavenAGI.KnowledgeContextByEntities
> = core.serialization.object({
    entities: core.serialization.list(ScopedEntity),
});

export declare namespace KnowledgeContextByEntities {
    export interface Raw {
        entities: ScopedEntity.Raw[];
    }
}
