// This file was auto-generated by Fern from our API Definition.

import type * as MavenAGI from "../../../../api/index";
import * as core from "../../../../core";
import * as serializers from "../../../index";
import { PreconditionGroupOperator } from "./PreconditionGroupOperator";

export const MetadataFilterGroup: core.serialization.ObjectSchema<
    serializers.MetadataFilterGroup.Raw,
    MavenAGI.MetadataFilterGroup
> = core.serialization.object({
    operator: PreconditionGroupOperator,
    filters: core.serialization.list(core.serialization.lazy(() => serializers.MetadataFilter)),
});

export declare namespace MetadataFilterGroup {
    export interface Raw {
        operator: PreconditionGroupOperator.Raw;
        filters: serializers.MetadataFilter.Raw[];
    }
}
