// This file was auto-generated by Fern from our API Definition.

import type * as MavenAGI from "../../../../api/index";
import * as core from "../../../../core";
import type * as serializers from "../../../index";
import { SettingsSchemaEntryBase } from "./SettingsSchemaEntryBase";
import { SettingsSchemaValidation } from "./SettingsSchemaValidation";

export const MultilineSettingsSchemaEntry: core.serialization.ObjectSchema<
    serializers.MultilineSettingsSchemaEntry.Raw,
    MavenAGI.MultilineSettingsSchemaEntry
> = core.serialization
    .object({
        defaultValue: core.serialization.string().optional(),
        validation: SettingsSchemaValidation.optional(),
    })
    .extend(SettingsSchemaEntryBase);

export declare namespace MultilineSettingsSchemaEntry {
    export interface Raw extends SettingsSchemaEntryBase.Raw {
        defaultValue?: string | null;
        validation?: SettingsSchemaValidation.Raw | null;
    }
}
