/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as MavenAGI from "../../../../api/index";
import * as core from "../../../../core";
import { EntityIdBase } from "./EntityIdBase";
import { NovelSystemEventNoId } from "./NovelSystemEventNoId";

export const NovelSystemEvent: core.serialization.ObjectSchema<
    serializers.NovelSystemEvent.Raw,
    MavenAGI.NovelSystemEvent
> = core.serialization
    .object({
        id: EntityIdBase,
    })
    .extend(NovelSystemEventNoId);

export declare namespace NovelSystemEvent {
    export interface Raw extends NovelSystemEventNoId.Raw {
        id: EntityIdBase.Raw;
    }
}
