// This file was auto-generated by Fern from our API Definition.

import type * as MavenAGI from "../../../../api/index";
import * as core from "../../../../core";
import type * as serializers from "../../../index";

export const NumberRange: core.serialization.ObjectSchema<serializers.NumberRange.Raw, MavenAGI.NumberRange> =
    core.serialization.object({
        greaterThanOrEqual: core.serialization.number().optional(),
        lessThan: core.serialization.number().optional(),
    });

export declare namespace NumberRange {
    export interface Raw {
        greaterThanOrEqual?: number | null;
        lessThan?: number | null;
    }
}
