// This file was auto-generated by Fern from our API Definition.

import type * as MavenAGI from "../../../../api/index";
import * as core from "../../../../core";
import * as serializers from "../../../index";
import { SettingsSchemaEntryBase } from "./SettingsSchemaEntryBase";

export const OneOfSettingsSchemaEntry: core.serialization.ObjectSchema<
    serializers.OneOfSettingsSchemaEntry.Raw,
    MavenAGI.OneOfSettingsSchemaEntry
> = core.serialization
    .object({
        unionOptions: core.serialization.lazy(() => serializers.SettingsSchemaDiscriminatedUnionOptions),
        defaultValue: core.serialization.unknown().optional(),
    })
    .extend(SettingsSchemaEntryBase);

export declare namespace OneOfSettingsSchemaEntry {
    export interface Raw extends SettingsSchemaEntryBase.Raw {
        unionOptions: serializers.SettingsSchemaDiscriminatedUnionOptions.Raw;
        defaultValue?: unknown | null;
    }
}
