// This file was auto-generated by Fern from our API Definition.

import type * as MavenAGI from "../../../../api/index";
import * as core from "../../../../core";
import type * as serializers from "../../../index";

export const Page: core.serialization.ObjectSchema<serializers.Page.Raw, MavenAGI.Page> = core.serialization.object({
    number: core.serialization.number(),
    size: core.serialization.number(),
    totalElements: core.serialization.number(),
    totalPages: core.serialization.number(),
});

export declare namespace Page {
    export interface Raw {
        number: number;
        size: number;
        totalElements: number;
        totalPages: number;
    }
}
