// This file was auto-generated by Fern from our API Definition.

import * as serializers from "../../../index";
import * as MavenAGI from "../../../../api/index";
import * as core from "../../../../core";
import { PreconditionGroupOperator } from "./PreconditionGroupOperator";

export const PreconditionGroup: core.serialization.ObjectSchema<
    serializers.PreconditionGroup.Raw,
    MavenAGI.PreconditionGroup
> = core.serialization.object({
    operator: PreconditionGroupOperator,
    preconditions: core.serialization.list(core.serialization.lazy(() => serializers.Precondition)),
});

export declare namespace PreconditionGroup {
    export interface Raw {
        operator: PreconditionGroupOperator.Raw;
        preconditions: serializers.Precondition.Raw[];
    }
}
