// This file was auto-generated by Fern from our API Definition.

import type * as MavenAGI from "../../../../api/index";
import * as core from "../../../../core";
import type * as serializers from "../../../index";

export const ResolutionStatus: core.serialization.Schema<serializers.ResolutionStatus.Raw, MavenAGI.ResolutionStatus> =
    core.serialization.enum_([
        "UNKNOWN",
        "ERROR",
        "IN_PROGRESS",
        "RESOLVED",
        "ESCALATED",
        "NEGATIVE_FEEDBACK",
        "INELIGIBLE",
    ]);

export declare namespace ResolutionStatus {
    export type Raw =
        | "UNKNOWN"
        | "ERROR"
        | "IN_PROGRESS"
        | "RESOLVED"
        | "ESCALATED"
        | "NEGATIVE_FEEDBACK"
        | "INELIGIBLE";
}
