// This file was auto-generated by Fern from our API Definition.

import type * as MavenAGI from "../../../../api/index";
import * as core from "../../../../core";
import * as serializers from "../../../index";

export const SettingsSchemaDiscriminatedUnionOptions: core.serialization.Schema<
    serializers.SettingsSchemaDiscriminatedUnionOptions.Raw,
    MavenAGI.SettingsSchemaDiscriminatedUnionOptions
> = core.serialization.list(core.serialization.lazyObject(() => serializers.SettingsSchemaDiscriminatedUnionOption));

export declare namespace SettingsSchemaDiscriminatedUnionOptions {
    export type Raw = serializers.SettingsSchemaDiscriminatedUnionOption.Raw[];
}
