// This file was auto-generated by Fern from our API Definition.

import type * as MavenAGI from "../../../../api/index";
import * as core from "../../../../core";
import type * as serializers from "../../../index";
import { VisibilityType } from "./VisibilityType";

export const SettingsSchemaEntryBase: core.serialization.ObjectSchema<
    serializers.SettingsSchemaEntryBase.Raw,
    MavenAGI.SettingsSchemaEntryBase
> = core.serialization.object({
    key: core.serialization.string(),
    displayName: core.serialization.string(),
    description: core.serialization.string().optional(),
    visibility: VisibilityType.optional(),
    required: core.serialization.boolean().optional(),
});

export declare namespace SettingsSchemaEntryBase {
    export interface Raw {
        key: string;
        displayName: string;
        description?: string | null;
        visibility?: VisibilityType.Raw | null;
        required?: boolean | null;
    }
}
