// This file was auto-generated by Fern from our API Definition.

import type * as MavenAGI from "../../../../api/index";
import * as core from "../../../../core";
import type * as serializers from "../../../index";

export const StringMembershipOperator: core.serialization.Schema<
    serializers.StringMembershipOperator.Raw,
    MavenAGI.StringMembershipOperator
> = core.serialization.enum_(["IN", "NOT_IN"]);

export declare namespace StringMembershipOperator {
    export type Raw = "IN" | "NOT_IN";
}
