/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as MavenAGI from "../../../../api/index";
import * as core from "../../../../core";
import { EntityIdBase } from "./EntityIdBase";
import { UserConversationMessageType } from "./UserConversationMessageType";
import { ConversationMessageBase } from "./ConversationMessageBase";

export const UserMessageBase: core.serialization.ObjectSchema<
    serializers.UserMessageBase.Raw,
    MavenAGI.UserMessageBase
> = core.serialization
    .object({
        userId: EntityIdBase,
        text: core.serialization.string(),
        userMessageType: UserConversationMessageType,
    })
    .extend(ConversationMessageBase);

export declare namespace UserMessageBase {
    export interface Raw extends ConversationMessageBase.Raw {
        userId: EntityIdBase.Raw;
        text: string;
        userMessageType: UserConversationMessageType.Raw;
    }
}
