// This file was auto-generated by Fern from our API Definition.

import type * as MavenAGI from "../../../../api/index";
import * as core from "../../../../core";
import type * as serializers from "../../../index";
import { StringMembershipOperator } from "./StringMembershipOperator";
import { UserEventName } from "./UserEventName";

export const UserEventNameCondition: core.serialization.ObjectSchema<
    serializers.UserEventNameCondition.Raw,
    MavenAGI.UserEventNameCondition
> = core.serialization.object({
    operator: StringMembershipOperator,
    names: core.serialization.list(UserEventName),
});

export declare namespace UserEventNameCondition {
    export interface Raw {
        operator: StringMembershipOperator.Raw;
        names: UserEventName.Raw[];
    }
}
