// This file was auto-generated by Fern from our API Definition.

import * as serializers from "../../../index";
import * as MavenAGI from "../../../../api/index";
import * as core from "../../../../core";
import { EntityIdFilter } from "./EntityIdFilter";
import { UserData } from "./UserData";

export const UserDataWithReference: core.serialization.ObjectSchema<
    serializers.UserDataWithReference.Raw,
    MavenAGI.UserDataWithReference
> = core.serialization
    .object({
        userId: EntityIdFilter,
    })
    .extend(UserData);

export declare namespace UserDataWithReference {
    export interface Raw extends UserData.Raw {
        userId: EntityIdFilter.Raw;
    }
}
