/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as MavenAGI from "../../../../api/index";
import * as core from "../../../../core";
import { Agent } from "../types/Agent";

export const Response: core.serialization.Schema<serializers.agents.list.Response.Raw, MavenAGI.Agent[]> =
    core.serialization.list(Agent);

export declare namespace Response {
    export type Raw = Agent.Raw[];
}
