// This file was auto-generated by Fern from our API Definition.

import type * as MavenAGI from "../../../../api/index";
import * as core from "../../../../core";
import * as serializers from "../../../index";
import { EntityId } from "../../commons/types/EntityId";
import { CharterChildrenExclusionPolicy } from "./CharterChildrenExclusionPolicy";
import { CharterStatus } from "./CharterStatus";
import { CharterType } from "./CharterType";

export const CharterSummary: core.serialization.ObjectSchema<serializers.CharterSummary.Raw, MavenAGI.CharterSummary> =
    core.serialization.object({
        charterId: EntityId,
        name: core.serialization.string(),
        precondition: core.serialization.lazy(() => serializers.PreconditionResponse).nullable(),
        parentCharterId: EntityId.nullable(),
        status: CharterStatus,
        type: CharterType.optional(),
        childrenExclusionPolicy: CharterChildrenExclusionPolicy.optional(),
        createdAt: core.serialization.date(),
        updatedAt: core.serialization.date(),
    });

export declare namespace CharterSummary {
    export interface Raw {
        charterId: EntityId.Raw;
        name: string;
        precondition?: serializers.PreconditionResponse.Raw | null;
        parentCharterId?: EntityId.Raw | null;
        status: CharterStatus.Raw;
        type?: CharterType.Raw | null;
        childrenExclusionPolicy?: CharterChildrenExclusionPolicy.Raw | null;
        createdAt: string;
        updatedAt: string;
    }
}
