// This file was auto-generated by Fern from our API Definition.

import type * as MavenAGI from "../../../../api/index";
import * as core from "../../../../core";
import type * as serializers from "../../../index";

export const CharterBase: core.serialization.ObjectSchema<serializers.CharterBase.Raw, MavenAGI.CharterBase> =
    core.serialization.object({
        name: core.serialization.string(),
        description: core.serialization.string().optional(),
        manual: core.serialization.string().optional(),
    });

export declare namespace CharterBase {
    export interface Raw {
        name: string;
        description?: string | null;
        manual?: string | null;
    }
}
